<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Kapital 1 Grundlæggende R | Analyse og visualisering af biologiske datasæt – 2026</title>
  <meta name="description" content="Course materials for Analyse og visualisering af biologiske datasæt 2026" />
  <meta name="generator" content="bookdown 0.45 and GitBook 2.6.7" />

  <meta property="og:title" content="Kapital 1 Grundlæggende R | Analyse og visualisering af biologiske datasæt – 2026" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/plots/ai_cover.jpeg" />
  <meta property="og:description" content="Course materials for Analyse og visualisering af biologiske datasæt 2026" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Kapital 1 Grundlæggende R | Analyse og visualisering af biologiske datasæt – 2026" />
  
  <meta name="twitter:description" content="Course materials for Analyse og visualisering af biologiske datasæt 2026" />
  <meta name="twitter:image" content="/plots/ai_cover.jpeg" />

<meta name="author" content="Sarah Rennie" />


<meta name="date" content="2025-12-14" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="rmarkdown.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/vembedr-0.1.5/css/vembedr.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="assets/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Visualisering_2026</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Lidt om kurset</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#outline"><i class="fa fa-check"></i>Outline</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#bed%C3%B8mmelse"><i class="fa fa-check"></i>Bedømmelse</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#bare-lidt-om-underviserne"><i class="fa fa-check"></i>Bare lidt om underviserne</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="baser.html"><a href="baser.html"><i class="fa fa-check"></i><b>1</b> Grundlæggende R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="baser.html"><a href="baser.html#inledning-til-kapitel"><i class="fa fa-check"></i><b>1.1</b> Inledning til kapitel</a></li>
<li class="chapter" data-level="1.2" data-path="baser.html"><a href="baser.html#rstudio"><i class="fa fa-check"></i><b>1.2</b> RStudio</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="baser.html"><a href="baser.html#de-forskellige-vinduer-i-rstudio"><i class="fa fa-check"></i><b>1.2.1</b> De forskellige vinduer i RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="baser.html"><a href="baser.html#working-directory"><i class="fa fa-check"></i><b>1.3</b> Working directory</a></li>
<li class="chapter" data-level="1.4" data-path="baser.html"><a href="baser.html#r-pakker"><i class="fa fa-check"></i><b>1.4</b> R pakker</a></li>
<li class="chapter" data-level="1.5" data-path="baser.html"><a href="baser.html#hvor-kommer-vores-data-fra"><i class="fa fa-check"></i><b>1.5</b> Hvor kommer vores data fra?</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="baser.html"><a href="baser.html#indbyggede-datas%C3%A6t"><i class="fa fa-check"></i><b>1.5.1</b> Indbyggede datasæt</a></li>
<li class="chapter" data-level="1.5.2" data-path="baser.html"><a href="baser.html#importering-af-data-fra-.txt-fil"><i class="fa fa-check"></i><b>1.5.2</b> Importering af data fra .txt fil</a></li>
<li class="chapter" data-level="1.5.3" data-path="baser.html"><a href="baser.html#importering-af-data-fra-excel"><i class="fa fa-check"></i><b>1.5.3</b> Importering af data fra Excel</a></li>
<li class="chapter" data-level="1.5.4" data-path="baser.html"><a href="baser.html#kaggle"><i class="fa fa-check"></i><b>1.5.4</b> Kaggle</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="baser.html"><a href="baser.html#beregninger-i-r"><i class="fa fa-check"></i><b>1.6</b> Beregninger i R</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="baser.html"><a href="baser.html#objekter"><i class="fa fa-check"></i><b>1.6.1</b> Objekter</a></li>
<li class="chapter" data-level="1.6.2" data-path="baser.html"><a href="baser.html#vektorer"><i class="fa fa-check"></i><b>1.6.2</b> Vektorer</a></li>
<li class="chapter" data-level="1.6.3" data-path="baser.html"><a href="baser.html#datatyper"><i class="fa fa-check"></i><b>1.6.3</b> Datatyper</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="baser.html"><a href="baser.html#dataframes"><i class="fa fa-check"></i><b>1.7</b> Dataframes</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="baser.html"><a href="baser.html#delm%C3%A6ngder-af-dataframes"><i class="fa fa-check"></i><b>1.7.1</b> Delmængder af dataframes</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="baser.html"><a href="baser.html#ifelse"><i class="fa fa-check"></i><b>1.8</b> If/else</a></li>
<li class="chapter" data-level="1.9" data-path="baser.html"><a href="baser.html#loops"><i class="fa fa-check"></i><b>1.9</b> Loops</a></li>
<li class="chapter" data-level="1.10" data-path="baser.html"><a href="baser.html#descriptive-statistics-beskrivende-statistik"><i class="fa fa-check"></i><b>1.10</b> Descriptive statistics / beskrivende statistik</a>
<ul>
<li class="chapter" data-level="1.10.1" data-path="baser.html"><a href="baser.html#simulere-data-fra-den-normalfordeling"><i class="fa fa-check"></i><b>1.10.1</b> Simulere data fra den normalfordeling</a></li>
<li class="chapter" data-level="1.10.2" data-path="baser.html"><a href="baser.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>1.10.2</b> Measures of central tendency</a></li>
<li class="chapter" data-level="1.10.3" data-path="baser.html"><a href="baser.html#tapply"><i class="fa fa-check"></i><b>1.10.3</b> <code>tapply()</code></a></li>
</ul></li>
<li class="chapter" data-level="1.11" data-path="baser.html"><a href="baser.html#statistike-tester"><i class="fa fa-check"></i><b>1.11</b> Statistike tester</a>
<ul>
<li class="chapter" data-level="1.11.1" data-path="baser.html"><a href="baser.html#p-v%C3%A6rdien"><i class="fa fa-check"></i><b>1.11.1</b> P-værdien</a></li>
<li class="chapter" data-level="1.11.2" data-path="baser.html"><a href="baser.html#korrelation"><i class="fa fa-check"></i><b>1.11.2</b> Korrelation</a></li>
<li class="chapter" data-level="1.11.3" data-path="baser.html"><a href="baser.html#test-for-uafh%C3%A6ngighed-chi-sq-test"><i class="fa fa-check"></i><b>1.11.3</b> Test for uafhængighed (chi-sq test)</a></li>
<li class="chapter" data-level="1.11.4" data-path="baser.html"><a href="baser.html#sample-t-test"><i class="fa fa-check"></i><b>1.11.4</b> 1 sample t-test</a></li>
<li class="chapter" data-level="1.11.5" data-path="baser.html"><a href="baser.html#sample-t-test-1"><i class="fa fa-check"></i><b>1.11.5</b> 2-sample t-test</a></li>
<li class="chapter" data-level="1.11.6" data-path="baser.html"><a href="baser.html#paired-t-test-parret-t-test"><i class="fa fa-check"></i><b>1.11.6</b> Paired t-test / parret t-test</a></li>
<li class="chapter" data-level="1.11.7" data-path="baser.html"><a href="baser.html#anova-variansanalyse"><i class="fa fa-check"></i><b>1.11.7</b> ANOVA (variansanalyse)</a></li>
<li class="chapter" data-level="1.11.8" data-path="baser.html"><a href="baser.html#line%C3%A6r-regression-linear-regression"><i class="fa fa-check"></i><b>1.11.8</b> Lineær regression / linear regression</a></li>
<li class="chapter" data-level="1.11.9" data-path="baser.html"><a href="baser.html#r-squared-bestemmelseskoefficient-koefficient-of-determination"><i class="fa fa-check"></i><b>1.11.9</b> R-squared bestemmelseskoefficient / koefficient of determination</a></li>
<li class="chapter" data-level="1.11.10" data-path="baser.html"><a href="baser.html#antagelser-ved-brug-af-line%C3%A6r-regression"><i class="fa fa-check"></i><b>1.11.10</b> Antagelser ved brug af lineær regression</a></li>
<li class="chapter" data-level="1.11.11" data-path="baser.html"><a href="baser.html#multiple-line%C3%A6r-regression"><i class="fa fa-check"></i><b>1.11.11</b> Multiple lineær regression</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="baser.html"><a href="baser.html#problemstillinger"><i class="fa fa-check"></i><b>1.12</b> Problemstillinger</a>
<ul>
<li class="chapter" data-level="1.12.1" data-path="baser.html"><a href="baser.html#quiz---basics"><i class="fa fa-check"></i><b>1.12.1</b> Quiz - Basics</a></li>
<li class="chapter" data-level="1.12.2" data-path="baser.html"><a href="baser.html#grundl%C3%A6ggende-r"><i class="fa fa-check"></i><b>1.12.2</b> Grundlæggende R</a></li>
<li class="chapter" data-level="1.12.3" data-path="baser.html"><a href="baser.html#kort-analyse-med-reaktionstider"><i class="fa fa-check"></i><b>1.12.3</b> Kort analyse med reaktionstider</a></li>
<li class="chapter" data-level="1.12.4" data-path="baser.html"><a href="baser.html#%C3%B8velse-med-co2"><i class="fa fa-check"></i><b>1.12.4</b> Øvelse med CO2</a></li>
<li class="chapter" data-level="1.12.5" data-path="baser.html"><a href="baser.html#ekstra-%C3%B8velser-med-andre-statistike-tests"><i class="fa fa-check"></i><b>1.12.5</b> Ekstra øvelser med andre statistike tests</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="rmarkdown.html"><a href="rmarkdown.html"><i class="fa fa-check"></i><b>2</b> Introduktion til R Markdown</a>
<ul>
<li class="chapter" data-level="2.1" data-path="rmarkdown.html"><a href="rmarkdown.html#inledning-til-kapitlet"><i class="fa fa-check"></i><b>2.1</b> Inledning til kapitlet</a></li>
<li class="chapter" data-level="2.2" data-path="rmarkdown.html"><a href="rmarkdown.html#hvad-er-r-markdown"><i class="fa fa-check"></i><b>2.2</b> Hvad er R Markdown?</a></li>
<li class="chapter" data-level="2.3" data-path="rmarkdown.html"><a href="rmarkdown.html#installere-r-markdown"><i class="fa fa-check"></i><b>2.3</b> Installere R Markdown</a></li>
<li class="chapter" data-level="2.4" data-path="rmarkdown.html"><a href="rmarkdown.html#videodemonstrationer"><i class="fa fa-check"></i><b>2.4</b> Videodemonstrationer</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="rmarkdown.html"><a href="rmarkdown.html#video-1"><i class="fa fa-check"></i><b>2.4.1</b> Video 1</a></li>
<li class="chapter" data-level="2.4.2" data-path="rmarkdown.html"><a href="rmarkdown.html#video-2"><i class="fa fa-check"></i><b>2.4.2</b> Video 2</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="rmarkdown.html"><a href="rmarkdown.html#opret-et-nyt-dokument-i-r-markdown"><i class="fa fa-check"></i><b>2.5</b> Opret et nyt dokument i R Markdown</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="rmarkdown.html"><a href="rmarkdown.html#yaml"><i class="fa fa-check"></i><b>2.5.1</b> YAML</a></li>
<li class="chapter" data-level="2.5.2" data-path="rmarkdown.html"><a href="rmarkdown.html#globale-muligheder"><i class="fa fa-check"></i><b>2.5.2</b> Globale muligheder</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="rmarkdown.html"><a href="rmarkdown.html#skriv-og-formatere-tekst"><i class="fa fa-check"></i><b>2.6</b> Skriv og formatere tekst</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="rmarkdown.html"><a href="rmarkdown.html#headers"><i class="fa fa-check"></i><b>2.6.1</b> Headers</a></li>
<li class="chapter" data-level="2.6.2" data-path="rmarkdown.html"><a href="rmarkdown.html#tilf%C3%B8je-en-liste"><i class="fa fa-check"></i><b>2.6.2</b> Tilføje en liste</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="rmarkdown.html"><a href="rmarkdown.html#knitte-kode"><i class="fa fa-check"></i><b>2.7</b> Knitte kode</a></li>
<li class="chapter" data-level="2.8" data-path="rmarkdown.html"><a href="rmarkdown.html#kode-chunks"><i class="fa fa-check"></i><b>2.8</b> Kode chunks</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="rmarkdown.html"><a href="rmarkdown.html#knit-l%C3%B8bende-f%C3%B8r-at-undg%C3%A5-problemer"><i class="fa fa-check"></i><b>2.8.1</b> Knit løbende før at undgå problemer</a></li>
<li class="chapter" data-level="2.8.2" data-path="rmarkdown.html"><a href="rmarkdown.html#chunk-indstillinger"><i class="fa fa-check"></i><b>2.8.2</b> Chunk indstillinger</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="rmarkdown.html"><a href="rmarkdown.html#r-beregninger-inden-for-teksten-i-dokumentet-inline-code"><i class="fa fa-check"></i><b>2.9</b> R beregninger inden for teksten i dokumentet (‘inline code’)</a></li>
<li class="chapter" data-level="2.10" data-path="rmarkdown.html"><a href="rmarkdown.html#working-directory-1"><i class="fa fa-check"></i><b>2.10</b> Working directory</a></li>
<li class="chapter" data-level="2.11" data-path="rmarkdown.html"><a href="rmarkdown.html#matematik"><i class="fa fa-check"></i><b>2.11</b> Matematik</a></li>
<li class="chapter" data-level="2.12" data-path="rmarkdown.html"><a href="rmarkdown.html#hyppigt-forekommende-fejl"><i class="fa fa-check"></i><b>2.12</b> Hyppigt forekommende fejl</a></li>
<li class="chapter" data-level="2.13" data-path="rmarkdown.html"><a href="rmarkdown.html#problemstillinger-1"><i class="fa fa-check"></i><b>2.13</b> Problemstillinger</a></li>
<li class="chapter" data-level="2.14" data-path="rmarkdown.html"><a href="rmarkdown.html#forberedelse-af-n%C3%A6ste-emnet-og-lektionen"><i class="fa fa-check"></i><b>2.14</b> Forberedelse af næste emnet og lektionen</a></li>
<li class="chapter" data-level="2.15" data-path="rmarkdown.html"><a href="rmarkdown.html#ekstra-information"><i class="fa fa-check"></i><b>2.15</b> Ekstra information</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="visual1.html"><a href="visual1.html"><i class="fa fa-check"></i><b>3</b> Visualisering - ggplot2 dag 1</a>
<ul>
<li class="chapter" data-level="3.1" data-path="visual1.html"><a href="visual1.html#l%C3%A6ringsm%C3%A5lene-og-videoer"><i class="fa fa-check"></i><b>3.1</b> Læringsmålene og videoer</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="visual1.html"><a href="visual1.html#hvad-er-ggplot2"><i class="fa fa-check"></i><b>3.1.1</b> Hvad er <strong>ggplot2</strong>?</a></li>
<li class="chapter" data-level="3.1.2" data-path="visual1.html"><a href="visual1.html#brugen-af-materialerne"><i class="fa fa-check"></i><b>3.1.2</b> Brugen af materialerne</a></li>
<li class="chapter" data-level="3.1.3" data-path="visual1.html"><a href="visual1.html#video-ressourcer"><i class="fa fa-check"></i><b>3.1.3</b> Video ressourcer</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="visual1.html"><a href="visual1.html#transition-fra-base-r-til-ggplot2"><i class="fa fa-check"></i><b>3.2</b> Transition fra base R til ggplot2</a></li>
<li class="chapter" data-level="3.3" data-path="visual1.html"><a href="visual1.html#vores-f%C3%B8rste-ggplot"><i class="fa fa-check"></i><b>3.3</b> Vores første ggplot</a></li>
<li class="chapter" data-level="3.4" data-path="visual1.html"><a href="visual1.html#lidt-om-ggplot2"><i class="fa fa-check"></i><b>3.4</b> Lidt om ggplot2</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="visual1.html"><a href="visual1.html#syntax"><i class="fa fa-check"></i><b>3.4.1</b> Syntax</a></li>
<li class="chapter" data-level="3.4.2" data-path="visual1.html"><a href="visual1.html#hvad-betyder-egentlig-grammar-of-graphics"><i class="fa fa-check"></i><b>3.4.2</b> Hvad betyder egentlig grammar of graphics?</a></li>
<li class="chapter" data-level="3.4.3" data-path="visual1.html"><a href="visual1.html#global-versus-lokal-%C3%A6stetik"><i class="fa fa-check"></i><b>3.4.3</b> Global versus lokal æstetik</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="visual1.html"><a href="visual1.html#specificere-etiketter-og-titel"><i class="fa fa-check"></i><b>3.5</b> Specificere etiketter og titel</a></li>
<li class="chapter" data-level="3.6" data-path="visual1.html"><a href="visual1.html#%C3%A6ndre-farver"><i class="fa fa-check"></i><b>3.6</b> Ændre farver</a></li>
<li class="chapter" data-level="3.7" data-path="visual1.html"><a href="visual1.html#%C3%A6ndre-tema"><i class="fa fa-check"></i><b>3.7</b> Ændre tema</a></li>
<li class="chapter" data-level="3.8" data-path="visual1.html"><a href="visual1.html#forskellige-geoms"><i class="fa fa-check"></i><b>3.8</b> Forskellige geoms</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="visual1.html"><a href="visual1.html#boxplot-geom_box"><i class="fa fa-check"></i><b>3.8.1</b> Boxplot (<code>geom_box</code>)</a></li>
<li class="chapter" data-level="3.8.2" data-path="visual1.html"><a href="visual1.html#barplot-geom_bar"><i class="fa fa-check"></i><b>3.8.2</b> Barplot (<code>geom_bar</code>)</a></li>
<li class="chapter" data-level="3.8.3" data-path="visual1.html"><a href="visual1.html#histogram-geom_histogram"><i class="fa fa-check"></i><b>3.8.3</b> Histogram (<code>geom_histogram</code>)</a></li>
<li class="chapter" data-level="3.8.4" data-path="visual1.html"><a href="visual1.html#density-geom_density"><i class="fa fa-check"></i><b>3.8.4</b> Density (<code>geom_density</code>)</a></li>
<li class="chapter" data-level="3.8.5" data-path="visual1.html"><a href="visual1.html#line-plot-geom_line"><i class="fa fa-check"></i><b>3.8.5</b> Line plot (<code>geom_line()</code>)</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="visual1.html"><a href="visual1.html#troubleshooting"><i class="fa fa-check"></i><b>3.9</b> Troubleshooting</a></li>
<li class="chapter" data-level="3.10" data-path="visual1.html"><a href="visual1.html#problemstillinger-2"><i class="fa fa-check"></i><b>3.10</b> Problemstillinger</a></li>
<li class="chapter" data-level="3.11" data-path="visual1.html"><a href="visual1.html#n%C3%A6ste-gang"><i class="fa fa-check"></i><b>3.11</b> Næste gang</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="visual2.html"><a href="visual2.html"><i class="fa fa-check"></i><b>4</b> Visualisering - ggplot2 dag 2</a>
<ul>
<li class="chapter" data-level="4.1" data-path="visual2.html"><a href="visual2.html#l%C3%A6ringsm%C3%A5l-og-videoer"><i class="fa fa-check"></i><b>4.1</b> Læringsmål og videoer</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="visual2.html"><a href="visual2.html#video-ressourcer-1"><i class="fa fa-check"></i><b>4.1.1</b> Video ressourcer</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="visual2.html"><a href="visual2.html#koordinat-systemer"><i class="fa fa-check"></i><b>4.2</b> Koordinat systemer</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="visual2.html"><a href="visual2.html#zoom-coord_cartesian-expand_limits"><i class="fa fa-check"></i><b>4.2.1</b> Zoom (<code>coord_cartesian()</code>, <code>expand_limits()</code>)</a></li>
<li class="chapter" data-level="4.2.2" data-path="visual2.html"><a href="visual2.html#transformering-af-akserne---log-sqrt-osv-scale_x_continuous."><i class="fa fa-check"></i><b>4.2.2</b> Transformering af akserne - log, sqrt osv (<code>scale_x_continuous</code>).</a></li>
<li class="chapter" data-level="4.2.3" data-path="visual2.html"><a href="visual2.html#flip-coordinates-coord_flip"><i class="fa fa-check"></i><b>4.2.3</b> Flip coordinates (<code>coord_flip</code>)</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="visual2.html"><a href="visual2.html#mere-om-farver-og-punkt-former"><i class="fa fa-check"></i><b>4.3</b> Mere om farver og punkt former</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="visual2.html"><a href="visual2.html#automatisk-farver"><i class="fa fa-check"></i><b>4.3.1</b> Automatisk farver</a></li>
<li class="chapter" data-level="4.3.2" data-path="visual2.html"><a href="visual2.html#manuelle-farver"><i class="fa fa-check"></i><b>4.3.2</b> Manuelle farver</a></li>
<li class="chapter" data-level="4.3.3" data-path="visual2.html"><a href="visual2.html#punkt-former"><i class="fa fa-check"></i><b>4.3.3</b> Punkt former</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="visual2.html"><a href="visual2.html#annotations-geom_text"><i class="fa fa-check"></i><b>4.4</b> Annotations (<code>geom_text</code>)</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="visual2.html"><a href="visual2.html#tilf%C3%B8jelse-af-etiketter-direkte-p%C3%A5-plottet."><i class="fa fa-check"></i><b>4.4.1</b> Tilføjelse af etiketter direkte på plottet.</a></li>
<li class="chapter" data-level="4.4.2" data-path="visual2.html"><a href="visual2.html#pakken-ggrepel-for-at-tilf%C3%B8je-tekst-labeller"><i class="fa fa-check"></i><b>4.4.2</b> Pakken <code>ggrepel</code> for at tilføje tekst labeller</a></li>
<li class="chapter" data-level="4.4.3" data-path="visual2.html"><a href="visual2.html#tilf%C3%B8jelse-af-rektangler-i-regioner-af-interesse-annotate"><i class="fa fa-check"></i><b>4.4.3</b> Tilføjelse af rektangler i regioner af interesse (<code>annotate</code>)</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="visual2.html"><a href="visual2.html#adskille-plots-med-facets-facet_gridfacet_wrap"><i class="fa fa-check"></i><b>4.5</b> Adskille plots med facets (<code>facet_grid</code>/<code>facet_wrap</code>)</a></li>
<li class="chapter" data-level="4.6" data-path="visual2.html"><a href="visual2.html#gemme-dit-plot"><i class="fa fa-check"></i><b>4.6</b> Gemme dit plot</a></li>
<li class="chapter" data-level="4.7" data-path="visual2.html"><a href="visual2.html#problemstillinger-3"><i class="fa fa-check"></i><b>4.7</b> Problemstillinger</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>5</b> Bearbejdning - tidyverse dag 1</a>
<ul>
<li class="chapter" data-level="5.1" data-path="data.html"><a href="data.html#id%C3%A9en-med-tidyverse"><i class="fa fa-check"></i><b>5.1</b> Idéen med tidyverse</a></li>
<li class="chapter" data-level="5.2" data-path="data.html"><a href="data.html#video-ressourcer-2"><i class="fa fa-check"></i><b>5.2</b> Video ressourcer</a></li>
<li class="chapter" data-level="5.3" data-path="data.html"><a href="data.html#oversigt-over-pakker"><i class="fa fa-check"></i><b>5.3</b> Oversigt over pakker</a></li>
<li class="chapter" data-level="5.4" data-path="data.html"><a href="data.html#principper-af-tidy-data"><i class="fa fa-check"></i><b>5.4</b> Principper af ‘tidy’ data</a></li>
<li class="chapter" data-level="5.5" data-path="data.html"><a href="data.html#lidt-om-tibbles"><i class="fa fa-check"></i><b>5.5</b> Lidt om <code>tibbles</code></a></li>
<li class="chapter" data-level="5.6" data-path="data.html"><a href="data.html#transition-fra-base-r-til-tidyverse"><i class="fa fa-check"></i><b>5.6</b> Transition fra base-R til tidyverse</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="data.html"><a href="data.html#om-titanic-datas%C3%A6ttet"><i class="fa fa-check"></i><b>5.6.1</b> Om <strong>Titanic</strong> datasættet</a></li>
<li class="chapter" data-level="5.6.2" data-path="data.html"><a href="data.html#titanic-reng%C3%B8ring"><i class="fa fa-check"></i><b>5.6.2</b> Titanic: Rengøring</a></li>
<li class="chapter" data-level="5.6.3" data-path="data.html"><a href="data.html#pipe"><i class="fa fa-check"></i><b>5.6.3</b> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="data.html"><a href="data.html#bearbejdning-af-data-dplyr"><i class="fa fa-check"></i><b>5.7</b> Bearbejdning af data: <code>dplyr</code></a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="data.html"><a href="data.html#dplyr-verbs-select"><i class="fa fa-check"></i><b>5.7.1</b> dplyr verbs: <code>select()</code></a></li>
<li class="chapter" data-level="5.7.2" data-path="data.html"><a href="data.html#dplyr-verbs-filter"><i class="fa fa-check"></i><b>5.7.2</b> dplyr verbs: <code>filter()</code></a></li>
<li class="chapter" data-level="5.7.3" data-path="data.html"><a href="data.html#sammenligningsoperatorer"><i class="fa fa-check"></i><b>5.7.3</b> Sammenligningsoperatorer</a></li>
<li class="chapter" data-level="5.7.4" data-path="data.html"><a href="data.html#kombinere-filter-og-select"><i class="fa fa-check"></i><b>5.7.4</b> Kombinere <code>filter()</code> og <code>select()</code></a></li>
<li class="chapter" data-level="5.7.5" data-path="data.html"><a href="data.html#dplyr-verbs-mutate"><i class="fa fa-check"></i><b>5.7.5</b> dplyr verbs: <code>mutate()</code></a></li>
<li class="chapter" data-level="5.7.6" data-path="data.html"><a href="data.html#rename"><i class="fa fa-check"></i><b>5.7.6</b> <code>rename()</code></a></li>
<li class="chapter" data-level="5.7.7" data-path="data.html"><a href="data.html#dplyr-verbs-recode"><i class="fa fa-check"></i><b>5.7.7</b> dplyr verbs: <code>recode()</code></a></li>
<li class="chapter" data-level="5.7.8" data-path="data.html"><a href="data.html#dplyr-verbs-arrange"><i class="fa fa-check"></i><b>5.7.8</b> dplyr verbs: <code>arrange()</code></a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="data.html"><a href="data.html#visualisering-bruge-som-input-i-ggplot2"><i class="fa fa-check"></i><b>5.8</b> Visualisering: bruge som input i ggplot2</a></li>
<li class="chapter" data-level="5.9" data-path="data.html"><a href="data.html#ekstra-funktioner-som-er-nyttige-at-vide"><i class="fa fa-check"></i><b>5.9</b> Ekstra funktioner som er nyttige at vide</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="data.html"><a href="data.html#pull"><i class="fa fa-check"></i><b>5.9.1</b> Pull</a></li>
<li class="chapter" data-level="5.9.2" data-path="data.html"><a href="data.html#slice"><i class="fa fa-check"></i><b>5.9.2</b> Slice</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="data.html"><a href="data.html#problemstillinger-4"><i class="fa fa-check"></i><b>5.10</b> Problemstillinger</a></li>
<li class="chapter" data-level="5.11" data-path="data.html"><a href="data.html#kommentarer"><i class="fa fa-check"></i><b>5.11</b> Kommentarer</a></li>
<li class="chapter" data-level="5.12" data-path="data.html"><a href="data.html#n%C3%A6ste-gange"><i class="fa fa-check"></i><b>5.12</b> Næste gange</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="data2.html"><a href="data2.html"><i class="fa fa-check"></i><b>6</b> Bearbejdning - tidyverse dag 2</a>
<ul>
<li class="chapter" data-level="6.1" data-path="data2.html"><a href="data2.html#introduktion-og-l%C3%A6ringsm%C3%A5lene"><i class="fa fa-check"></i><b>6.1</b> Introduktion og læringsmålene</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="data2.html"><a href="data2.html#l%C3%A6ringsm%C3%A5lene"><i class="fa fa-check"></i><b>6.1.1</b> Læringsmålene</a></li>
<li class="chapter" data-level="6.1.2" data-path="data2.html"><a href="data2.html#videoer"><i class="fa fa-check"></i><b>6.1.2</b> Videoer</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="data2.html"><a href="data2.html#kombinationen-af-group_by-og-summarise-i-dplyr-pakken"><i class="fa fa-check"></i><b>6.2</b> Kombinationen af <code>group_by()</code> og <code>summarise()</code> i <code>dplyr</code>-pakken</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="data2.html"><a href="data2.html#reference-af-summarise-funktioner"><i class="fa fa-check"></i><b>6.2.1</b> Reference af <code>summarise()</code>-funktioner</a></li>
<li class="chapter" data-level="6.2.2" data-path="data2.html"><a href="data2.html#flere-summeringsstatistikker-p%C3%A5-%C3%A9n-gang"><i class="fa fa-check"></i><b>6.2.2</b> Flere summeringsstatistikker på én gang</a></li>
<li class="chapter" data-level="6.2.3" data-path="data2.html"><a href="data2.html#mere-avanceret-group_by"><i class="fa fa-check"></i><b>6.2.3</b> Mere avanceret <code>group_by()</code></a></li>
<li class="chapter" data-level="6.2.4" data-path="data2.html"><a href="data2.html#funktionen-ungroup"><i class="fa fa-check"></i><b>6.2.4</b> Funktionen <code>ungroup()</code></a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="data2.html"><a href="data2.html#pivot_longerpivot_wider-fra-tidyr-pakken"><i class="fa fa-check"></i><b>6.3</b> <code>pivot_longer()</code>/<code>pivot_wider()</code> fra <code>tidyr</code>-pakken</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="data2.html"><a href="data2.html#oversigt-over-tidyr-pakken"><i class="fa fa-check"></i><b>6.3.1</b> Oversigt over <code>tidyr</code> pakken</a></li>
<li class="chapter" data-level="6.3.2" data-path="data2.html"><a href="data2.html#reshape-data-fra-wide-til-long-med-pivot_longer"><i class="fa fa-check"></i><b>6.3.2</b> Reshape data fra wide til long med <code>pivot_longer()</code></a></li>
<li class="chapter" data-level="6.3.3" data-path="data2.html"><a href="data2.html#separate"><i class="fa fa-check"></i><b>6.3.3</b> <code>separate()</code></a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="data2.html"><a href="data2.html#eksempel-titanic-opsummeringsstatistikker"><i class="fa fa-check"></i><b>6.4</b> Eksempel: Titanic opsummeringsstatistikker</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="data2.html"><a href="data2.html#pivot_wider"><i class="fa fa-check"></i><b>6.4.1</b> <code>pivot_wider()</code></a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="data2.html"><a href="data2.html#left_join-forbinde-dataframes"><i class="fa fa-check"></i><b>6.5</b> <code>left_join()</code>: forbinde dataframes</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="data2.html"><a href="data2.html#left_join-fra-dplyr-pakken"><i class="fa fa-check"></i><b>6.5.1</b> <code>left_join()</code> fra dplyr-pakken</a></li>
<li class="chapter" data-level="6.5.2" data-path="data2.html"><a href="data2.html#anvend-left_join-p%C3%A5-vores-datas%C3%A6t."><i class="fa fa-check"></i><b>6.5.2</b> Anvend <code>left_join()</code> på vores datasæt.</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="data2.html"><a href="data2.html#problemstillinger-5"><i class="fa fa-check"></i><b>6.6</b> Problemstillinger</a></li>
<li class="chapter" data-level="6.7" data-path="data2.html"><a href="data2.html#ekstra-links"><i class="fa fa-check"></i><b>6.7</b> Ekstra links</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html"><i class="fa fa-check"></i><b>7</b> Functional programming med purrr-pakken</a>
<ul>
<li class="chapter" data-level="7.1" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#inledning-og-l%C3%A6ringsm%C3%A5lene"><i class="fa fa-check"></i><b>7.1</b> Inledning og læringsmålene</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#videorressourcer"><i class="fa fa-check"></i><b>7.1.1</b> Videorressourcer</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#iterative-processer-med-map-funktioner"><i class="fa fa-check"></i><b>7.2</b> Iterative processer med <code>map()</code> funktioner</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#introduktion-til-map-funktioner"><i class="fa fa-check"></i><b>7.2.1</b> Introduktion til <code>map()</code> funktioner</a></li>
<li class="chapter" data-level="7.2.2" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#reference-for-de-forskellige-map-funktioner"><i class="fa fa-check"></i><b>7.2.2</b> Reference for de forskellige map-funktioner</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#brugerdefinerede-funktioner"><i class="fa fa-check"></i><b>7.3</b> Brugerdefinerede funktioner</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#simple-funktioner"><i class="fa fa-check"></i><b>7.3.1</b> Simple funktioner</a></li>
<li class="chapter" data-level="7.3.2" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#brugerdefinerede-funktioner-med-map"><i class="fa fa-check"></i><b>7.3.2</b> Brugerdefinerede funktioner med map</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#effekten-af-map-p%C3%A5-vektorer-dataframe-eller-liste"><i class="fa fa-check"></i><b>7.4</b> Effekten af <code>map()</code> på vektorer, dataframe eller liste</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#input-vektor"><i class="fa fa-check"></i><b>7.4.1</b> <strong>Input: vektor</strong></a></li>
<li class="chapter" data-level="7.4.2" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#input-dataframe"><i class="fa fa-check"></i><b>7.4.2</b> <strong>Input: dataframe</strong></a></li>
<li class="chapter" data-level="7.4.3" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#input-liste"><i class="fa fa-check"></i><b>7.4.3</b> <strong>Input: liste</strong></a></li>
<li class="chapter" data-level="7.4.4" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#liste-af-dataframes"><i class="fa fa-check"></i><b>7.4.4</b> <strong>Liste af dataframes</strong></a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#nesting-med-nest"><i class="fa fa-check"></i><b>7.5</b> Nesting med <code>nest()</code></a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#anvendelse-af-map-med-nested-data"><i class="fa fa-check"></i><b>7.5.1</b> Anvendelse af map() med nested data</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#andre-brugbar-purrr"><i class="fa fa-check"></i><b>7.6</b> Andre brugbar purrr</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#map2-funktion-for-to-input-vektorer"><i class="fa fa-check"></i><b>7.6.1</b> <code>map2()</code> funktion for to input-vektorer</a></li>
<li class="chapter" data-level="7.6.2" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#map_if-til-transformering-af-numeriske-variabler"><i class="fa fa-check"></i><b>7.6.2</b> <code>map_if()</code> til transformering af numeriske variabler</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#problemstillinger-6"><i class="fa fa-check"></i><b>7.7</b> Problemstillinger</a></li>
<li class="chapter" data-level="7.8" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#ekstra-notater"><i class="fa fa-check"></i><b>7.8</b> Ekstra notater</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="visualisering-af-trends.html"><a href="visualisering-af-trends.html"><i class="fa fa-check"></i><b>8</b> Visualisering af trends</a>
<ul>
<li class="chapter" data-level="8.1" data-path="visualisering-af-trends.html"><a href="visualisering-af-trends.html#indledning"><i class="fa fa-check"></i><b>8.1</b> Indledning</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="visualisering-af-trends.html"><a href="visualisering-af-trends.html#videoressourcer"><i class="fa fa-check"></i><b>8.1.1</b> Videoressourcer</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="visualisering-af-trends.html"><a href="visualisering-af-trends.html#nest-og-map-eksempel-med-korrelation"><i class="fa fa-check"></i><b>8.2</b> <code>nest()</code> og <code>map()</code>: eksempel med korrelation</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="visualisering-af-trends.html"><a href="visualisering-af-trends.html#korrelation-over-flere-datas%C3%A6t-p%C3%A5-en-gang"><i class="fa fa-check"></i><b>8.2.1</b> Korrelation over flere datasæt på en gang</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="visualisering-af-trends.html"><a href="visualisering-af-trends.html#line%C3%A6r-regression---visualisering"><i class="fa fa-check"></i><b>8.3</b> Lineær regression - visualisering</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="visualisering-af-trends.html"><a href="visualisering-af-trends.html#line%C3%A6re-trends"><i class="fa fa-check"></i><b>8.3.1</b> Lineære trends</a></li>
<li class="chapter" data-level="8.3.2" data-path="visualisering-af-trends.html"><a href="visualisering-af-trends.html#geom_smooth-lm-trendlinjer"><i class="fa fa-check"></i><b>8.3.2</b> <code>geom_smooth()</code>: <code>lm</code> trendlinjer</a></li>
<li class="chapter" data-level="8.3.3" data-path="visualisering-af-trends.html"><a href="visualisering-af-trends.html#geom_smooth-flere-lm-trendlinjer-p%C3%A5-samme-plot"><i class="fa fa-check"></i><b>8.3.3</b> <code>geom_smooth()</code>: flere <code>lm</code> trendlinjer på samme plot</a></li>
<li class="chapter" data-level="8.3.4" data-path="visualisering-af-trends.html"><a href="visualisering-af-trends.html#trendlinjer-med-methodloess"><i class="fa fa-check"></i><b>8.3.4</b> Trendlinjer med <code>method=="loess"</code></a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="visualisering-af-trends.html"><a href="visualisering-af-trends.html#plot-linear-regression-estimates"><i class="fa fa-check"></i><b>8.4</b> Plot linear regression estimates</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="visualisering-af-trends.html"><a href="visualisering-af-trends.html#anvendelse-af-lm-over-nestede-datas%C3%A6t"><i class="fa fa-check"></i><b>8.4.1</b> Anvendelse af <code>lm()</code> over nestede datasæt</a></li>
<li class="chapter" data-level="8.4.2" data-path="visualisering-af-trends.html"><a href="visualisering-af-trends.html#funktionen-glue-til-at-tilf%C3%B8je-etiketter"><i class="fa fa-check"></i><b>8.4.2</b> Funktionen <code>glue()</code> til at tilføje etiketter</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="visualisering-af-trends.html"><a href="visualisering-af-trends.html#multipel-regression-og-model-sammenligning"><i class="fa fa-check"></i><b>8.5</b> Multipel regression og model sammenligning</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="visualisering-af-trends.html"><a href="visualisering-af-trends.html#anova-til-at-sammenligne-de-forskellige-modeller"><i class="fa fa-check"></i><b>8.5.1</b> <code>anova</code> til at sammenligne de forskellige modeller</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="visualisering-af-trends.html"><a href="visualisering-af-trends.html#resource"><i class="fa fa-check"></i><b>8.6</b> Resource</a></li>
<li class="chapter" data-level="8.7" data-path="visualisering-af-trends.html"><a href="visualisering-af-trends.html#problemstillinger-7"><i class="fa fa-check"></i><b>8.7</b> Problemstillinger</a></li>
<li class="chapter" data-level="8.8" data-path="visualisering-af-trends.html"><a href="visualisering-af-trends.html#ekstra"><i class="fa fa-check"></i><b>8.8</b> Ekstra</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="clustering.html"><a href="clustering.html"><i class="fa fa-check"></i><b>9</b> Clustering</a>
<ul>
<li class="chapter" data-level="9.1" data-path="clustering.html"><a href="clustering.html#indledning-og-l%C3%A6ringsm%C3%A5l"><i class="fa fa-check"></i><b>9.1</b> Indledning og læringsmål</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="clustering.html"><a href="clustering.html#l%C3%A6ringsm%C3%A5l"><i class="fa fa-check"></i><b>9.1.1</b> Læringsmål</a></li>
<li class="chapter" data-level="9.1.2" data-path="clustering.html"><a href="clustering.html#indledning-til-kapitel"><i class="fa fa-check"></i><b>9.1.2</b> Indledning til kapitel</a></li>
<li class="chapter" data-level="9.1.3" data-path="clustering.html"><a href="clustering.html#video-ressourcer-3"><i class="fa fa-check"></i><b>9.1.3</b> Video ressourcer</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="clustering.html"><a href="clustering.html#method-1-k-means-clustering"><i class="fa fa-check"></i><b>9.2</b> Method 1: K-means clustering</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="clustering.html"><a href="clustering.html#hvordan-fungerer-kmeans"><i class="fa fa-check"></i><b>9.2.1</b> Hvordan fungerer kmeans?</a></li>
<li class="chapter" data-level="9.2.2" data-path="clustering.html"><a href="clustering.html#withinbetween-sum-of-squares"><i class="fa fa-check"></i><b>9.2.2</b> Within/between sum of squares</a></li>
<li class="chapter" data-level="9.2.3" data-path="clustering.html"><a href="clustering.html#k%C3%B8r-k-means-i-r"><i class="fa fa-check"></i><b>9.2.3</b> Kør k-means i R</a></li>
<li class="chapter" data-level="9.2.4" data-path="clustering.html"><a href="clustering.html#ryd-op-i-k-means-resultaterne-med-pakken-broom"><i class="fa fa-check"></i><b>9.2.4</b> Ryd op i k-means resultaterne med pakken <code>broom</code></a></li>
<li class="chapter" data-level="9.2.5" data-path="clustering.html"><a href="clustering.html#plotcentroids"><i class="fa fa-check"></i><b>9.2.5</b> Plot cluster centroids</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="clustering.html"><a href="clustering.html#kmeans-hvor-mange-clusters"><i class="fa fa-check"></i><b>9.3</b> Kmeans: hvor mange clusters?</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="clustering.html"><a href="clustering.html#f%C3%A5-broom-output-for-forskellige-antal-clusters"><i class="fa fa-check"></i><b>9.3.1</b> Få Broom output for forskellige antal clusters</a></li>
<li class="chapter" data-level="9.3.2" data-path="clustering.html"><a href="clustering.html#elbow-plot-glance"><i class="fa fa-check"></i><b>9.3.2</b> Elbow plot (glance)</a></li>
<li class="chapter" data-level="9.3.3" data-path="clustering.html"><a href="clustering.html#automatisk-beslutning-med-pakken-nbclust"><i class="fa fa-check"></i><b>9.3.3</b> Automatisk beslutning med pakken <code>NbClust</code></a></li>
<li class="chapter" data-level="9.3.4" data-path="clustering.html"><a href="clustering.html#visualisering-af-de-forskellige-antal-clusters-augment"><i class="fa fa-check"></i><b>9.3.4</b> Visualisering af de forskellige antal clusters (augment)</a></li>
<li class="chapter" data-level="9.3.5" data-path="clustering.html"><a href="clustering.html#nestmap-ramme-fra-sidste-gang"><i class="fa fa-check"></i><b>9.3.5</b> Nest/map-ramme fra sidste gang</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="clustering.html"><a href="clustering.html#metode-2-hierarchical-clustering"><i class="fa fa-check"></i><b>9.4</b> Metode 2: Hierarchical clustering</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="clustering.html"><a href="clustering.html#v%C3%A6lge-%C3%B8nsket-antal-clusters"><i class="fa fa-check"></i><b>9.4.1</b> Vælge ønsket antal clusters</a></li>
<li class="chapter" data-level="9.4.2" data-path="clustering.html"><a href="clustering.html#lav-et-p%C3%A6nt-plot-af-dendrogrammet-med-ggplot2"><i class="fa fa-check"></i><b>9.4.2</b> Lav et pænt plot af dendrogrammet med ggplot2</a></li>
<li class="chapter" data-level="9.4.3" data-path="clustering.html"><a href="clustering.html#afpr%C3%B8ve-andre-metoder-p%C3%A5-hierachical-clustering"><i class="fa fa-check"></i><b>9.4.3</b> Afprøve andre metoder på hierachical clustering</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="clustering.html"><a href="clustering.html#problemstillinger-8"><i class="fa fa-check"></i><b>9.5</b> Problemstillinger</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html"><i class="fa fa-check"></i><b>10</b> Principal component analysis (PCA)</a>
<ul>
<li class="chapter" data-level="10.1" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html#indledning-og-l%C3%A6ringsm%C3%A5lene"><i class="fa fa-check"></i><b>10.1</b> Indledning og læringsmålene</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html#l%C3%A6ringsm%C3%A5lene-1"><i class="fa fa-check"></i><b>10.1.1</b> Læringsmålene</a></li>
<li class="chapter" data-level="10.1.2" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html#introduktion-til-kapitlet"><i class="fa fa-check"></i><b>10.1.2</b> Introduktion til kapitlet</a></li>
<li class="chapter" data-level="10.1.3" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html#videoressourcer-1"><i class="fa fa-check"></i><b>10.1.3</b> Videoressourcer</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html#hvad-er-principal-component-analysis-pca"><i class="fa fa-check"></i><b>10.2</b> Hvad er principal component analysis (PCA)?</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html#problemet-med-h%C3%B8j-dimensionelle-plots"><i class="fa fa-check"></i><b>10.2.1</b> Problemet med høj-dimensionelle plots</a></li>
<li class="chapter" data-level="10.2.2" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html#id%C3%A9en-bag-pca-projektion-p%C3%A5-nye-akser"><i class="fa fa-check"></i><b>10.2.2</b> Idéen bag PCA: Projektion på nye akser</a></li>
<li class="chapter" data-level="10.2.3" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html#simpelt-eksempel-med-to-dimensioner"><i class="fa fa-check"></i><b>10.2.3</b> Simpelt eksempel med to dimensioner</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html#fit-pca-to-data-in-r-med-prcomp"><i class="fa fa-check"></i><b>10.3</b> Fit PCA to data in R med <code>prcomp()</code></a></li>
<li class="chapter" data-level="10.4" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html#integrering-af-pca-resultater-med-broom-pakken"><i class="fa fa-check"></i><b>10.4</b> Integrering af PCA-resultater med broom-pakken</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html#lave-plot-af-principal-componenets"><i class="fa fa-check"></i><b>10.4.1</b> Lave plot af principal componenets</a></li>
<li class="chapter" data-level="10.4.2" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html#forklarede-variance"><i class="fa fa-check"></i><b>10.4.2</b> Forklarede variance</a></li>
<li class="chapter" data-level="10.4.3" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html#rotationsmatrix-bidragene-fra-de-forskellige-variabler"><i class="fa fa-check"></i><b>10.4.3</b> Rotationsmatrix: bidragene fra de forskellige variabler</a></li>
<li class="chapter" data-level="10.4.4" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html#pakken-factoextra"><i class="fa fa-check"></i><b>10.4.4</b> Pakken <code>factoextra</code></a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html#problemstillinger-9"><i class="fa fa-check"></i><b>10.5</b> Problemstillinger</a></li>
<li class="chapter" data-level="10.6" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html#ekstra-l%C3%A6sning"><i class="fa fa-check"></i><b>10.6</b> Ekstra læsning</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://sarah-ku.github.io/Visualisering_2026" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Analyse og visualisering af biologiske datasæt – 2026</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="baser" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Kapital 1</span> Grundlæggende R<a href="baser.html#baser" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><img src="plots/logo_baseR.png" width="20%" height="20%" /></p>
<p>“Det er ikke, fordi noget er svært, at vi ikke tør, det er, fordi vi ikke tør, at noget er svært.” - Seneca</p>
<div id="inledning-til-kapitel" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Inledning til kapitel<a href="baser.html#inledning-til-kapitel" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Først og fremmest, velkommen til kurset! Det her dokument er kursusnotaterne, som indeholder bla. videoer, forklaringer og problemstillinger, og vi opdaterer dem løbende gennem hele forløbet. Vær opmærksom på, at der også vil være flere dokumenter på Absalon vedrørende forelæsninger, workshops og løsningerne til øvelserne.</p>
<p>I dette kapitel opsummerer vi nogle grundlæggende elementer inden for R og statistik, der betragtes som forudsætninger i dette kursus. Selvom vi i kurset skifter hurtigt over til tidyverse-pakken, som erstatter en stor del af funktionaliteten fra den såkaldte base-R, er det stadig vigtigt at have et grundlæggende kendskab til base-R. Hvis du har begrænset erfaring med base-R, anbefaler vi, at du bruger ekstra tid ud over de første mødegange for at nå det nødvendige niveau.</p>
<p>For at bestå kurset forventes det ikke, at du kender til alle detaljer og teorier bag de statistiske metoder, men at du kan anvende dem hensigtsmæssigt i praksis via R og fortolke resultaterne korrekte. Der vil være masser af muligheder for at øve dig I at anvende statistik hele vejen gennem kurset, og under eksamen vil vi ikke stille spørgsmål om metoder, der ikke er dækket i de forskellige øvelser (herunder workshop-opgaver). Lineær regression vil også blive gennemgået i forelæsningerne så vær ikke bekymret hvis du ikke har set det før.</p>
<div class="checklist">
<p>Se gerne også “Quiz - Grundlæggende” på Absalon for at tjekke din forståelse og udfylde eventuelle huller i din viden (OBS! Quizzen er tilgængelig kort tid inden kurset starter).</p>
</div>
</div>
<div id="rstudio" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> RStudio<a href="baser.html#rstudio" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<blockquote>
<blockquote>
<p>Vi kommer til at være afhængig af RStudio til at arbejde med bl.a. R Markdown dokumenter. R Markdown er emnet i vores næste lektion og vi går igennem hele emnet så at alle er med uanset jeres mulige tidligere erfaringer.&lt;&lt;</p>
</blockquote>
</blockquote>
<p>Det allerførste du burde gør, hvis du ikke har installeret RStudio på din computer, er at downloade det gratis på nettet:</p>
<p><a href="https://www.rstudio.com/products/rstudio/download/#download" class="uri">https://www.rstudio.com/products/rstudio/download/#download</a></p>
<p>Følg venligst RStudios egne anvisninger til at få det installeret. Bemærk, at installering af RStudio er ikke det samme som at have R installeret på din computer - man skal installere dem begge to og RStudio er afhængig af R men ikke omvendt.</p>
<div id="de-forskellige-vinduer-i-rstudio" class="section level3 hasAnchor" number="1.2.1">
<h3><span class="header-section-number">1.2.1</span> De forskellige vinduer i RStudio<a href="baser.html#de-forskellige-vinduer-i-rstudio" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-3"></span>
<img src="plots/RStudio_overview.png" alt="Image source: https://epirhandbook.com/en/r-basics.html" width="90%" height="90%" />
<p class="caption">
Figure 1.1: Image source: <a href="https://epirhandbook.com/en/r-basics.html" class="uri">https://epirhandbook.com/en/r-basics.html</a>
</p>
</div>
<p>Du kan læse følgende for at få en overblik om de fire forskellige vinduer i RStudio:</p>
<p><a href="https://bookdown.org/ndphillips/YaRrr/the-four-rstudio-windows.html" class="uri">https://bookdown.org/ndphillips/YaRrr/the-four-rstudio-windows.html</a></p>
<p>Her er et kort oversigt:</p>
<ul>
<li>Man skriver kode i <strong>Source</strong> (øverst til venstre)</li>
<li>Man kører kode ved at tryk CMD+ENTER (eller WIN-KEY+ENTER)</li>
<li>Koder køres ind i <strong>Console</strong> (som plejer at være nederst til venstre, selvom det er øverst til højere i billedet). Man kan også skrive koder direkte i Console, men det anbefales generelt ikke, når koden ikke bliver gemt.</li>
<li><strong>Environment</strong> - her kan man se blandt andet, alle objekter i Workspace.</li>
</ul>
</div>
</div>
<div id="working-directory" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Working directory<a href="baser.html#working-directory" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Når man arbejder på et projekt, er det ofte nyttigt at vide, den <em>working directory</em> som R arbejder i - det er den mappe, hvor R forsøger at åbne eller gemme filer, medmindre man angiver et andet sted.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="baser.html#cb1-1" tabindex="-1"></a><span class="fu">getwd</span>() <span class="co">#se nuværende working directory</span></span>
<span id="cb1-2"><a href="baser.html#cb1-2" tabindex="-1"></a><span class="fu">list.dirs</span>(<span class="at">path =</span> <span class="st">&quot;.&quot;</span>, <span class="at">recursive =</span> <span class="cn">FALSE</span>) <span class="co">#se alle mapper indenfor din working directory</span></span>
<span id="cb1-3"><a href="baser.html#cb1-3" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;~/Documents/&quot;</span>) <span class="co">#angiv en ny working directory (C:/Users/myname/Documents hvis man bruger Windows)</span></span></code></pre></div>
<p>Hvis man bruger Windows, skal man husk at skrive en path på følgende måde:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="baser.html#cb2-1" tabindex="-1"></a><span class="co">#notrun</span></span>
<span id="cb2-2"><a href="baser.html#cb2-2" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;C:/Users/myname/Documents&quot;</span>) <span class="co">#enten med /</span></span>
<span id="cb2-3"><a href="baser.html#cb2-3" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;C:</span><span class="sc">\\</span><span class="st">Users</span><span class="sc">\\</span><span class="st">myname</span><span class="sc">\\</span><span class="st">Documents&quot;</span>) <span class="co">#eller med \\</span></span></code></pre></div>
<p><strong>OBS</strong>: vi som underiser bruger Mac/Linux, så hvis der er vigtige ting at huske for at bruge Windows, kan vi selvfølgelig også tilføje det her. Bemærk dog, at de allerfleste ting ved R programmering og tidyverse er ens uanset om man bruger Windows eller Mac.</p>
</div>
<div id="r-pakker" class="section level2 hasAnchor" number="1.4">
<h2><span class="header-section-number">1.4</span> R pakker<a href="baser.html#r-pakker" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>R pakker er i grund og bunden hver kun en samling af funktioner (eller datasæt i nogle tilfælde), der udvider, hvad er tilgængelige i base-R (den R man få, uden at indlæse en pakke). I R er der mange tusind R pakker (op mod 100,000), der er tilgængelige på <strong>CRAN</strong> (<a href="https://cran.r-project.org/" class="uri">https://cran.r-project.org/</a>). Inden for biologisk forskning er der også mange flere pakker på <strong>Bioconductor</strong> (<a href="https://www.bioconductor.org/" class="uri">https://www.bioconductor.org/</a>), og i mange tilfælde kan R pakker også installeres direkte fra <strong>Github</strong>.</p>
<p>I dette kursus arbejder vi meget med en pakke der hedder <strong>tidyverse</strong>. <strong>tidyverse</strong> er i sig selv faktisk en samling af otte R pakker, som indlæses på en gang. Inden du indlæse pakken, skal du først sikre dig, at pakken er installeret på systemet ved følgende kommando:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="baser.html#cb3-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;tidyverse&quot;</span>)</span></code></pre></div>
<p>Alle pakker på <strong>CRAN</strong> er installeret på samme måde. Når du faktisk gerne vil bruge en R pakke, skal du først indlæse den ved at bruge <code>library()</code>:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="baser.html#cb4-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## ── Attaching core tidyverse pa
## ✔ dplyr     1.1.4     ✔ readr     2.1.5
## ✔ forcats   1.0.1     ✔ stringr   1.6.0
## ✔ ggplot2   4.0.0     ✔ tibble    3.3.0
## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
## ✔ purrr     1.2.0     
## ── Conflicts ─────────────────
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
## ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<p>Vi kommer til at arbejde med <strong>tidyverse</strong> pakker fra kapitel tre (vi starter med <strong>ggplot2</strong>), <strong>så det er en god idé at har tidyverse installeret allerede nu</strong>, fordi nogle gange kan det tage lang tid til at installere eller opdatere de mange andre mulige pakker, der <strong>tidyverse</strong> er afhængig af.</p>
<p>Vær opmærksom på, at der nogle gange opstår konflikter når det samme funktionnavn findes i flere pakker - for eksempel, funktionen <code>filter()</code> findes indenfor to forskellige pakker, nemlig <code>dplyr</code> og <code>stats</code>. Når du skriver <code>filter()</code> så ved R ikke, hvilken pakke du mener. I dette tilfælde kan du være mere konkret og skriver desuden pakkenavnen <code>dplyr::filter()</code> eller <code>stats:filter()</code> i stedet for bare <code>filter()</code>.</p>
<p>Det er god praksis at indlæse alle pakker du andvender i toppen / i begyndelsen af din script. På denne måde få man hurtig overblik over, hvilke pakker er nødvendige for at få din kode til at fungere.</p>
</div>
<div id="hvor-kommer-vores-data-fra" class="section level2 hasAnchor" number="1.5">
<h2><span class="header-section-number">1.5</span> Hvor kommer vores data fra?<a href="baser.html#hvor-kommer-vores-data-fra" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>De forskellige datasæt vi kommer til at arbejde med i kurset stammer fra mange forskellige steder og er ikke nødvendigvis altid relateret til biologi.</p>
<div id="indbyggede-datasæt" class="section level3 hasAnchor" number="1.5.1">
<h3><span class="header-section-number">1.5.1</span> Indbyggede datasæt<a href="baser.html#indbyggede-datas%C3%A6t" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>I R er der mange indbygget datasæt som er meget brugbart for at vise analyse- og programmeringskoncepter, hvilket gøre dem især populært til undervisning. Indbyggede datasæt er ofte tilgængligt indenfor mange pakker, men <code>library(datasets)</code> er den hyppigst brugt (der er også mange indenfor <code>library(ggplot2)</code>). For eksempel, for at indlæse <code>iris</code>-datasættet, kan man bruge <code>data()</code>:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="baser.html#cb6-1" tabindex="-1"></a><span class="fu">library</span>(datasets)</span>
<span id="cb6-2"><a href="baser.html#cb6-2" tabindex="-1"></a><span class="fu">data</span>(iris)</span></code></pre></div>
<p>Derefter er en <em>dataframe</em> med navnet <code>iris</code> tilgængelig og er også gemt som <em>objekt</em> i <em>workspacen</em> - se den “Environment” fane på højere side i RStudio, eller indtaste <code>ls()</code>, så burde du kunne se objektet. Man kan kun arbejde med objekter når de er en del af workspacen.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="baser.html#cb7-1" tabindex="-1"></a><span class="fu">head</span>(iris) <span class="co">#first few rows</span></span></code></pre></div>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="baser.html#cb9-1" tabindex="-1"></a><span class="fu">tail</span>(iris) <span class="co">#last few rows</span></span></code></pre></div>
<pre><code>##     Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
## 145          6.7         3.3          5.7         2.5 virginica
## 146          6.7         3.0          5.2         2.3 virginica
## 147          6.3         2.5          5.0         1.9 virginica
## 148          6.5         3.0          5.2         2.0 virginica
## 149          6.2         3.4          5.4         2.3 virginica
## 150          5.9         3.0          5.1         1.8 virginica</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="baser.html#cb11-1" tabindex="-1"></a><span class="fu">str</span>(iris) <span class="co">#structure</span></span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    150 obs. of  5 variables:
##  $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
##  $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
##  $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
##  $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
##  $ Species     : Factor w/ 3 levels &quot;setosa&quot;,&quot;versicolor&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="baser.html#cb13-1" tabindex="-1"></a><span class="fu">summary</span>(iris) <span class="co">#summary per column</span></span></code></pre></div>
<pre><code>##   Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
##  Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
##  1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
##  Median :5.800   Median :3.000   Median :4.350   Median :1.300  
##  Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
##  3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
##  Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
##        Species  
##  setosa    :50  
##  versicolor:50  
##  virginica :50  
##                 
##                 
## </code></pre>
</div>
<div id="importering-af-data-fra-.txt-fil" class="section level3 hasAnchor" number="1.5.2">
<h3><span class="header-section-number">1.5.2</span> Importering af data fra .txt fil<a href="baser.html#importering-af-data-fra-.txt-fil" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Det er meget hyppigt, at man har sin data i formen af en .txt fil eller .xlsx fil på sin computer. En nem måde at åbne en .txt fil er ved at bruge <code>read.table()</code>, som i nedenstående:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="baser.html#cb15-1" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;mydata.txt&quot;</span>) <span class="co">#indlæse data filen mydata.txt som er i nuværende working directory</span></span>
<span id="cb15-2"><a href="baser.html#cb15-2" tabindex="-1"></a><span class="fu">head</span>(data)</span></code></pre></div>
<p>Hvis datasættet i filen har kolonnenavne, skal man huske at bruge <code>header=T</code> for at undgå at den første række med kolonnenavne blive fortolket som data / observationer i stedet for kolonner.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="baser.html#cb16-1" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;mydata.txt&quot;</span>,<span class="at">header=</span>T) <span class="co">#indlæse data filen mydata.txt som er i nuværende working directory</span></span>
<span id="cb16-2"><a href="baser.html#cb16-2" tabindex="-1"></a><span class="fu">head</span>(data)</span></code></pre></div>
</div>
<div id="importering-af-data-fra-excel" class="section level3 hasAnchor" number="1.5.3">
<h3><span class="header-section-number">1.5.3</span> Importering af data fra Excel<a href="baser.html#importering-af-data-fra-excel" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Der findes også en hjælpsom pakke fra <strong>tidyverset</strong>, som hedder <strong>readxl</strong>, der kan indlæse Excel-ark direkte ind i R:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="baser.html#cb17-1" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb17-2"><a href="baser.html#cb17-2" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;data.xlsx&quot;</span>)</span>
<span id="cb17-3"><a href="baser.html#cb17-3" tabindex="-1"></a>data</span></code></pre></div>
<p>Hvis man gerne vil referere til en bestemt ark, så kan man bruge en ekstra indstilling:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="baser.html#cb18-1" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb18-2"><a href="baser.html#cb18-2" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;data.xlsx&quot;</span>, <span class="at">sheet =</span> <span class="dv">1</span>)</span>
<span id="cb18-3"><a href="baser.html#cb18-3" tabindex="-1"></a>data</span></code></pre></div>
</div>
<div id="kaggle" class="section level3 hasAnchor" number="1.5.4">
<h3><span class="header-section-number">1.5.4</span> Kaggle<a href="baser.html#kaggle" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Hvis du kan lige at øve dig i statistik analyse (udover kurset), er Kaggle en fantastisk ressource til at finde forskellige datasæt. I rigtige mange tilfælde kan man også finde analyser some andre har lavet i R (eller f.eks. Python), hvilket kan være meget inspirerende.</p>
<p>Link hvis interesseret: <a href="https://www.kaggle.com/" class="uri">https://www.kaggle.com/</a></p>
</div>
</div>
<div id="beregninger-i-r" class="section level2 hasAnchor" number="1.6">
<h2><span class="header-section-number">1.6</span> Beregninger i R<a href="baser.html#beregninger-i-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Her er nogle helt grundlæggende koncepter når man arbejder med R. Du må selvfølgelig gerne springe sektionen over, hvis du allerede har meget erfaring med base-R. Men det kunne være godt at tjekke, om der noget du er ikke stødt på endu. En god tilgang kunne være at arbejde gennem problemstillingerne nedenfor og bruger følgende notater som en reference.</p>
<div id="objekter" class="section level3 hasAnchor" number="1.6.1">
<h3><span class="header-section-number">1.6.1</span> Objekter<a href="baser.html#objekter" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Man definere en objekt med brug af <code>&lt;-</code> tegn</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="baser.html#cb19-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="co">#x er defineret som 2</span></span></code></pre></div>
<p>OBS! En objekts værdi kan nemt overskrives - vær opmærksomt på rækkefølgen af de udførte kommandoer:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="baser.html#cb20-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="co">#x er defineret som 2</span></span>
<span id="cb20-2"><a href="baser.html#cb20-2" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">4</span> <span class="co">#nu er x omdefineret som 4</span></span></code></pre></div>
<p>Man kan også kombinere to objekter:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="baser.html#cb21-1" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="dv">5</span> <span class="co">#a er defineret som 5</span></span>
<span id="cb21-2"><a href="baser.html#cb21-2" tabindex="-1"></a>b <span class="ot">&lt;-</span> a <span class="sc">+</span> x</span>
<span id="cb21-3"><a href="baser.html#cb21-3" tabindex="-1"></a>b <span class="co"># 5 + 4</span></span></code></pre></div>
<pre><code>## [1] 9</code></pre>
<p>Vær opmærksom på, at man kan ændre på <code>a</code>, uden at <code>b</code> ændre sig automatisk:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="baser.html#cb23-1" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="dv">23</span></span>
<span id="cb23-2"><a href="baser.html#cb23-2" tabindex="-1"></a>b <span class="co">#stadig 5 + 4</span></span></code></pre></div>
<pre><code>## [1] 9</code></pre>
<p>Hvis man vil opdatere <code>b</code>, så skal den defineres igen:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="baser.html#cb25-1" tabindex="-1"></a>b <span class="ot">&lt;-</span> a <span class="sc">+</span> x</span>
<span id="cb25-2"><a href="baser.html#cb25-2" tabindex="-1"></a>b <span class="co"># 23 + 4</span></span></code></pre></div>
<pre><code>## [1] 27</code></pre>
</div>
<div id="vektorer" class="section level3 hasAnchor" number="1.6.2">
<h3><span class="header-section-number">1.6.2</span> Vektorer<a href="baser.html#vektorer" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>I R laver man en vektor med <code>c()</code>, hvor man adskiller de forskellige elementer med en komma, som i eksempeln nedenfor:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="baser.html#cb27-1" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>) <span class="co">#sæt objektet &#39;a&#39; til at være en vektor baseret af en talkæde</span></span>
<span id="cb27-2"><a href="baser.html#cb27-2" tabindex="-1"></a>a</span></code></pre></div>
<pre><code>## [1] 1 2 3 4 5</code></pre>
<!-- Man kan også  -->
<!-- ```{r} -->
<!-- a <- 1:5 -->
<!-- ``` -->
<p>Man er ikke begrænset til tal:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="baser.html#cb29-1" tabindex="-1"></a>c <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;cat&quot;</span>,<span class="st">&quot;mouse&quot;</span>,<span class="st">&quot;horse&quot;</span>,<span class="st">&quot;sheep&quot;</span>,<span class="st">&quot;dog&quot;</span>)</span>
<span id="cb29-2"><a href="baser.html#cb29-2" tabindex="-1"></a>c</span></code></pre></div>
<pre><code>## [1] &quot;cat&quot;   &quot;mouse&quot; &quot;horse&quot; &quot;sheep&quot; &quot;dog&quot;</code></pre>
</div>
<div id="datatyper" class="section level3 hasAnchor" number="1.6.3">
<h3><span class="header-section-number">1.6.3</span> Datatyper<a href="baser.html#datatyper" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Når vi kommer til at arbejde med visualiseringer og data er det vigtigt at have styr på datatyper i vores datasættet. For eksempel har vektoren <code>c("cat","mouse","horse","sheep","dog")</code> ovenpå typen <code>character</code> (forkortet <code>chr</code>) og ikke <code>numeric</code> som <code>c(1,2,3,4,5)</code> (forkortet <code>num</code>):</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="baser.html#cb31-1" tabindex="-1"></a><span class="fu">is.numeric</span>(c)</span>
<span id="cb31-2"><a href="baser.html#cb31-2" tabindex="-1"></a><span class="do">## [1] FALSE</span></span>
<span id="cb31-3"><a href="baser.html#cb31-3" tabindex="-1"></a><span class="fu">is.character</span>(c)</span>
<span id="cb31-4"><a href="baser.html#cb31-4" tabindex="-1"></a><span class="do">## [1] TRUE</span></span></code></pre></div>
<p>Her er en list af de vigtigste datatyper:</p>
<table>
<colgroup>
<col width="33%" />
<col width="41%" />
<col width="25%" />
</colgroup>
<thead>
<tr class="header">
<th>Datatype</th>
<th>Navn</th>
<th>Beskrivelse</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>int</code></td>
<td>integer</td>
<td>kun hel tal <code>c(-1,0,1,2,3)</code></td>
</tr>
<tr class="even">
<td><code>lgl</code></td>
<td>logical</td>
<td><code>TRUE, TRUE, FALSE, TRUE, FALSE</code></td>
</tr>
<tr class="odd">
<td><code>chr</code></td>
<td>character</td>
<td><code>c("Bob","Sally","Brian",...)</code></td>
</tr>
<tr class="even">
<td><code>fct</code></td>
<td>factor</td>
<td>bestemte niveauer e.g. <code>Species</code>: <code>c("setosa","versicola")</code></td>
</tr>
<tr class="odd">
<td><code>dbl</code></td>
<td>double</td>
<td>Tal fk. c(<code>4.3902</code>, <code>3.12</code>, <code>4.5</code>)</td>
</tr>
<tr class="even">
<td><code>lst</code></td>
<td>list</td>
<td>forskellige data typer og specifikke elementer kombineret med <code>[[i]]</code> <code>[[1]] [1] c("red","blue")</code> <code>[[2]] [1] TRUE</code> <code>[[3]] [1] c(3,2.3,1.459)</code></td>
</tr>
</tbody>
</table>
<p>En datatype, der burde få særlig opmærksomhed er <code>fct</code> (factor). I følgende vektor <code>tea_coffee</code> har vi tekst, men blandt de fem elementer er der kun to forskellige niveauer (nemlig “tea” og “coffee”).</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="baser.html#cb32-1" tabindex="-1"></a>tea_coffee <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;tea&quot;</span>,<span class="st">&quot;tea&quot;</span>,<span class="st">&quot;coffee&quot;</span>,<span class="st">&quot;coffee&quot;</span>,<span class="st">&quot;tea&quot;</span>)</span>
<span id="cb32-2"><a href="baser.html#cb32-2" tabindex="-1"></a><span class="fu">is.factor</span>(tea_coffee)</span>
<span id="cb32-3"><a href="baser.html#cb32-3" tabindex="-1"></a><span class="do">## [1] FALSE</span></span>
<span id="cb32-4"><a href="baser.html#cb32-4" tabindex="-1"></a>tea_coffee</span>
<span id="cb32-5"><a href="baser.html#cb32-5" tabindex="-1"></a><span class="do">## [1] &quot;tea&quot;    &quot;tea&quot;    &quot;coffee&quot; &quot;coffee&quot; &quot;tea&quot;</span></span></code></pre></div>
<p>Vi vil derfor gerne fortælle R, at <code>tea_coffee</code> indeholder ikke kun tilfældig tekst men at der er en struktur bag indholdet. Derfor bruger vi funktionen <code>as.factor</code> for at lave vektoren om til datatypen <code>fct</code>.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="baser.html#cb33-1" tabindex="-1"></a>tea_coffee <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(tea_coffee)</span>
<span id="cb33-2"><a href="baser.html#cb33-2" tabindex="-1"></a><span class="fu">is.factor</span>(tea_coffee)</span>
<span id="cb33-3"><a href="baser.html#cb33-3" tabindex="-1"></a><span class="do">## [1] TRUE</span></span>
<span id="cb33-4"><a href="baser.html#cb33-4" tabindex="-1"></a>tea_coffee</span>
<span id="cb33-5"><a href="baser.html#cb33-5" tabindex="-1"></a><span class="do">## [1] tea    tea    coffee coffee tea   </span></span>
<span id="cb33-6"><a href="baser.html#cb33-6" tabindex="-1"></a><span class="do">## Levels: coffee tea</span></span></code></pre></div>
<p>De ‘ekstra’ oplysninger man har når en variabel er en factor bliver vigtigt når man arbejder med visualiseringer - f.eks. hvis vi gerne vil lave et barplot hvor man vil adskille søjlerne efter de to niveauer “tea” og “coffee” (visualiseringer er emnet af lektion 3).</p>
</div>
</div>
<div id="dataframes" class="section level2 hasAnchor" number="1.7">
<h2><span class="header-section-number">1.7</span> Dataframes<a href="baser.html#dataframes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><a href="http://www.r-tutor.com/r-introduction/data-frame" class="uri">http://www.r-tutor.com/r-introduction/data-frame</a></p>
<p>Mange af de ting, som vi laver i R tager udgangspunkten i dataframes (eller datarammer).</p>
<!-- height <-  c(140,187,154,132,165) -->
<!-- age <- c(34,31,25,43,29) -->
<!-- score <- c(56,82,48,75,79) -->
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="baser.html#cb34-1" tabindex="-1"></a>mydf <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="st">&quot;personID&quot;</span> <span class="ot">=</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="st">&quot;height&quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">140</span>,<span class="dv">187</span>,<span class="dv">154</span>,<span class="dv">132</span>,<span class="dv">165</span>), <span class="st">&quot;age&quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">34</span>,<span class="dv">31</span>,<span class="dv">25</span>,<span class="dv">43</span>,<span class="dv">29</span>))</span>
<span id="cb34-2"><a href="baser.html#cb34-2" tabindex="-1"></a>mydf</span></code></pre></div>
<pre><code>##   personID height age
## 1        1    140  34
## 2        2    187  31
## 3        3    154  25
## 4        4    132  43
## 5        5    165  29</code></pre>
<p>Man kan få adgang til variabler i en dataframe via dollar tegn <code>$</code>, f.eks. <code>personID</code> fra datarammen <code>mydf</code>:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="baser.html#cb36-1" tabindex="-1"></a>mydf<span class="sc">$</span>personID</span></code></pre></div>
<pre><code>## [1] 1 2 3 4 5</code></pre>
<p>Husk, at vores dataframe, ligesom et matrix (i R: <code>matrix()</code>) har to dimensioner - række og kolonner. Forskellen mellem en matrix og en dataramme er, at datarammer kan indeholde mange forskellige datatyper (herunder numeriske, faktorer, karakterer osv.), mens en matrix indeholder kun numeriske data. For eksempel, alle variabler i den ovenstående dataframe er numeriske, men vi kan godt tilføje en variabel som er ikke-numeriske:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="baser.html#cb38-1" tabindex="-1"></a>mydf<span class="sc">$</span>colour <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;red&quot;</span>,<span class="st">&quot;blue&quot;</span>,<span class="st">&quot;green&quot;</span>,<span class="st">&quot;orange&quot;</span>,<span class="st">&quot;purple&quot;</span>) <span class="co">#make new variable which is non-numeric</span></span>
<span id="cb38-2"><a href="baser.html#cb38-2" tabindex="-1"></a>mydf</span></code></pre></div>
<pre><code>##   personID height age colour
## 1        1    140  34    red
## 2        2    187  31   blue
## 3        3    154  25  green
## 4        4    132  43 orange
## 5        5    165  29 purple</code></pre>
<p>Derefter er <code>mydf</code> en dataframe, der blander forskellige datatyper. Følgende objekt er til gengæld en matrix:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="baser.html#cb40-1" tabindex="-1"></a><span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>), </span>
<span id="cb40-2"><a href="baser.html#cb40-2" tabindex="-1"></a>    <span class="at">nrow=</span><span class="dv">3</span>,</span>
<span id="cb40-3"><a href="baser.html#cb40-3" tabindex="-1"></a>    <span class="at">ncol=</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    4
## [2,]    2    5
## [3,]    3    6</code></pre>
<p>Som beskrevet tidligere kan en matrix kun indeholde numeriske data før at gøre matematiske operationer mulig (matrix multiplikation osv.). Men, i dette kursus beskæftiger vi os primært med dataframes (som bliver kaldt for tibbles i <strong>tidyverse</strong>).</p>
<div id="delmængder-af-dataframes" class="section level3 hasAnchor" number="1.7.1">
<h3><span class="header-section-number">1.7.1</span> Delmængder af dataframes<a href="baser.html#delm%C3%A6ngder-af-dataframes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Selvom vi kommer til at se på det igen når vi at arbejder med pakken <strong>tidyverse</strong>, er det vigtigt at forstå, hvordan man laver en delmængde i base-R. Det er et koncept som ofte skaber forvirring.</p>
<p>Når man vil gerne har en bestemt delmængde af en vector, bruger man firkantet paranteser <code>[ ]</code>. Følgende kode giver os de første to værdier fra vectoren <code>a</code>:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="baser.html#cb42-1" tabindex="-1"></a>a[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] 1 2</code></pre>
<p>Bemærk, mens vektorer har kun en dimension, <strong>har dataframes to dimensioner</strong>. Når man skal lave en delmægde af en dataframe, skal man derfor fortælle R, hvilke rækker og hvilke kolonner skal være med.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="baser.html#cb44-1" tabindex="-1"></a>mydf[indekser af rækker, indekser af kolonner]  <span class="co">#kør ikke, kun beskrivende kode</span></span></code></pre></div>
<p>For eksempel, hvis vi vil have de første to observationer af kun den anden variabel, skriver man følgende:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="baser.html#cb45-1" tabindex="-1"></a>mydf[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="dv">2</span>]  <span class="co">#første to rækker (observationer), kun anden kolonne (variabel)</span></span></code></pre></div>
<pre><code>## [1] 140 187</code></pre>
<p>Hvis vi vil beholde de første to observationer af alle variabler, kan den anden plads være tom:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="baser.html#cb47-1" tabindex="-1"></a>mydf[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, ]  <span class="co">#første to rækker, alle kolonner</span></span></code></pre></div>
<pre><code>##   personID height age colour
## 1        1    140  34    red
## 2        2    187  31   blue</code></pre>
<p>Vi kan også angive et kolonnenavn direkte:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="baser.html#cb49-1" tabindex="-1"></a>mydf[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>,<span class="st">&quot;height&quot;</span>]</span></code></pre></div>
<pre><code>## [1] 140 187</code></pre>
<p>Man kan få en delmængde af rækkerne ved at:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="baser.html#cb51-1" tabindex="-1"></a>mydf[mydf<span class="sc">$</span>height<span class="sc">&gt;=</span><span class="dv">165</span>,] <span class="co">#alle rækker i datarammen med height = 165 eller højere</span></span></code></pre></div>
<pre><code>##   personID height age colour
## 2        2    187  31   blue
## 5        5    165  29 purple</code></pre>
<p>Her er en tabel af komparativer, som bliver gentaget når vi kommer til at lave delmængder i <strong>tidyverse</strong>:</p>
<table>
<thead>
<tr class="header">
<th>Komparativ</th>
<th>Beskrivelse</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>&lt;</code></td>
<td>mindre end / less than</td>
</tr>
<tr class="even">
<td><code>&gt;</code></td>
<td>større end / greater than</td>
</tr>
<tr class="odd">
<td><code>&lt;=</code></td>
<td>mindre end eller lig med / less than or equal to</td>
</tr>
<tr class="even">
<td><code>&gt;=</code></td>
<td>større end eller lig med / greater than or equal to</td>
</tr>
<tr class="odd">
<td><code>==</code></td>
<td>lig med / equal to</td>
</tr>
<tr class="even">
<td><code>!=</code></td>
<td>ikke lig med / not equal to</td>
</tr>
<tr class="odd">
<td><code>&amp;</code></td>
<td>og / and</td>
</tr>
<tr class="even">
<td><code>%in%</code></td>
<td>en del af / part of</td>
</tr>
<tr class="odd">
<td><code>|</code></td>
<td>eller / or</td>
</tr>
<tr class="even">
<td><code>!</code></td>
<td>ikke / not</td>
</tr>
</tbody>
</table>
<p>Komparativen <code>%in%</code> er særlig brugbart og værd at huske:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="baser.html#cb53-1" tabindex="-1"></a>mydf[mydf<span class="sc">$</span>personID <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">5</span>),] <span class="co">#alle personer med personID 1,3 eller 5 </span></span></code></pre></div>
<pre><code>##   personID height age colour
## 1        1    140  34    red
## 3        3    154  25  green
## 5        5    165  29 purple</code></pre>
<p>Her er et eksempel, hvordan man bruger udråbstegnet: personer med personID, der ikke er 1,3 eller 5:</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="baser.html#cb55-1" tabindex="-1"></a>mydf[<span class="sc">!</span>(mydf<span class="sc">$</span>personID <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">5</span>)),] <span class="co">#alle personer med personID 2 eller 4</span></span></code></pre></div>
<pre><code>##   personID height age colour
## 2        2    187  31   blue
## 4        4    132  43 orange</code></pre>
</div>
</div>
<div id="ifelse" class="section level2 hasAnchor" number="1.8">
<h2><span class="header-section-number">1.8</span> If/else<a href="baser.html#ifelse" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If/else kodekonstruktioner er til at udføre forskellige handlinger baseret på om en bestemt betingelse er opfyldt. For eksempel, <code>if</code> med betingelsen <code>number &gt; 0</code>:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="baser.html#cb57-1" tabindex="-1"></a>number <span class="ot">&lt;-</span> <span class="dv">42</span></span>
<span id="cb57-2"><a href="baser.html#cb57-2" tabindex="-1"></a><span class="cf">if</span> (number <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb57-3"><a href="baser.html#cb57-3" tabindex="-1"></a>    <span class="fu">print</span>(<span class="st">&quot;Number is positive&quot;</span>)</span>
<span id="cb57-4"><a href="baser.html#cb57-4" tabindex="-1"></a>  }</span></code></pre></div>
<pre><code>## [1] &quot;Number is positive&quot;</code></pre>
<p>Hvis betingelsen er sand, udføres den handling indenfor <code>{ }</code>, dvs. “Number is positive” printes.</p>
<p>If/else konstruktioner gør det samme, men hvis betingelsen er ikke opfyldt, udføres en alternativ handling:</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="baser.html#cb59-1" tabindex="-1"></a>number <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">5</span></span>
<span id="cb59-2"><a href="baser.html#cb59-2" tabindex="-1"></a><span class="cf">if</span> (number <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb59-3"><a href="baser.html#cb59-3" tabindex="-1"></a>    <span class="fu">print</span>(<span class="st">&quot;Number is positive&quot;</span>)</span>
<span id="cb59-4"><a href="baser.html#cb59-4" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb59-5"><a href="baser.html#cb59-5" tabindex="-1"></a>    <span class="fu">print</span>(<span class="st">&quot;Number is not positive&quot;</span>)</span>
<span id="cb59-6"><a href="baser.html#cb59-6" tabindex="-1"></a>  }</span></code></pre></div>
<pre><code>## [1] &quot;Number is not positive&quot;</code></pre>
<p>Man kan også opnå samme resultatet med at bruge den alternative funktion <code>ifelse</code>:</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="baser.html#cb61-1" tabindex="-1"></a>number <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb61-2"><a href="baser.html#cb61-2" tabindex="-1"></a>numbers_of_interest <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">7</span>)</span>
<span id="cb61-3"><a href="baser.html#cb61-3" tabindex="-1"></a><span class="fu">ifelse</span>(<span class="at">test =</span> number <span class="sc">%in%</span> numbers_of_interest, </span>
<span id="cb61-4"><a href="baser.html#cb61-4" tabindex="-1"></a>       <span class="at">yes =</span> <span class="st">&quot;Number is interesting&quot;</span>,</span>
<span id="cb61-5"><a href="baser.html#cb61-5" tabindex="-1"></a>       <span class="at">no =</span>  <span class="st">&quot;Number is uninteresting&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Number is interesting&quot;</code></pre>
<p>Man behøver ikke at skrive ordene “test”, “yes” og “no” hver gang, så længe man bruger rækkefølgen af argumenterne lige som funktionen forventer:</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="baser.html#cb63-1" tabindex="-1"></a><span class="fu">ifelse</span>(number <span class="sc">%in%</span> numbers_of_interest, </span>
<span id="cb63-2"><a href="baser.html#cb63-2" tabindex="-1"></a>       <span class="st">&quot;Number is interesting&quot;</span>,</span>
<span id="cb63-3"><a href="baser.html#cb63-3" tabindex="-1"></a>       <span class="st">&quot;Number is uninteresting&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Number is interesting&quot;</code></pre>
</div>
<div id="loops" class="section level2 hasAnchor" number="1.9">
<h2><span class="header-section-number">1.9</span> Loops<a href="baser.html#loops" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>I base-R kan man laver simple loops (løkke) med følgende konstruktion:</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="baser.html#cb65-1" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) {</span>
<span id="cb65-2"><a href="baser.html#cb65-2" tabindex="-1"></a>    <span class="fu">print</span>(i)</span>
<span id="cb65-3"><a href="baser.html#cb65-3" tabindex="-1"></a>  }</span></code></pre></div>
<pre><code>## [1] 1
## [1] 2
## [1] 3
## [1] 4
## [1] 5</code></pre>
<p>Loops bliver et stort emne senere i kurset (under emnet 8/9).</p>
</div>
<div id="descriptive-statistics-beskrivende-statistik" class="section level2 hasAnchor" number="1.10">
<h2><span class="header-section-number">1.10</span> Descriptive statistics / beskrivende statistik<a href="baser.html#descriptive-statistics-beskrivende-statistik" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="simulere-data-fra-den-normalfordeling" class="section level3 hasAnchor" number="1.10.1">
<h3><span class="header-section-number">1.10.1</span> Simulere data fra den normalfordeling<a href="baser.html#simulere-data-fra-den-normalfordeling" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Hvis du har brug for at vide mere om den normalfordeling: <a href="http://www.r-tutor.com/elementary-statistics/probability-distributions/normal-distribution" class="uri">http://www.r-tutor.com/elementary-statistics/probability-distributions/normal-distribution</a></p>
<p>Man kan nemt lave sin egne ‘fake’ data ved at simulere det fra en fordeling, der typisk er normalfordelingen, da den er den mest almindelige fordeling i den virkelige verden (husk den klassiske klokkeform). I R kan man anvender funktionen <code>rnorm</code> til at simulere data. Først angiver man antallet af observationer, og derefter den gennemsnitlige værdi og standardafvigelsen (sd), som er de to nødvendige parametre for at beskrive en normalfordeling.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="baser.html#cb67-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">25</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>) <span class="co">#standard normalfordeling</span></span>
<span id="cb67-2"><a href="baser.html#cb67-2" tabindex="-1"></a>x <span class="co">#så har vi 25 værdier fra en normal distribution med mean = 0 og standard deviation = 1</span></span></code></pre></div>
<pre><code>##  [1] -1.26259321  1.03604350 -0.24083737 -0.71147387  1.17265243  0.57736405
##  [7] -1.78858624  1.35838366  4.77780328 -0.84746609  1.97716756  2.17180024
## [13]  1.55851236 -0.01483794  1.34326749 -1.04440099  0.45133505 -0.35687889
## [19]  0.71587272  1.13024961  0.32939008  0.54742019 -0.49036921  1.46669631
## [25] -0.64821683</code></pre>
<p>I stedet for at kigge på alle værdier på én gang, vil vi måske kun kigge på de første (eller sidste) værdier:</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="baser.html#cb69-1" tabindex="-1"></a><span class="fu">head</span>(x) <span class="co">#første 6</span></span>
<span id="cb69-2"><a href="baser.html#cb69-2" tabindex="-1"></a><span class="do">## [1] -1.2625932  1.0360435 -0.2408374 -0.7114739  1.1726524  0.5773640</span></span>
<span id="cb69-3"><a href="baser.html#cb69-3" tabindex="-1"></a><span class="fu">tail</span>(x) <span class="co">#sidste 6</span></span>
<span id="cb69-4"><a href="baser.html#cb69-4" tabindex="-1"></a><span class="do">## [1]  1.1302496  0.3293901  0.5474202 -0.4903692  1.4666963 -0.6482168</span></span>
<span id="cb69-5"><a href="baser.html#cb69-5" tabindex="-1"></a>x[<span class="dv">1</span>] <span class="co">#første værdi</span></span>
<span id="cb69-6"><a href="baser.html#cb69-6" tabindex="-1"></a><span class="do">## [1] -1.262593</span></span>
<span id="cb69-7"><a href="baser.html#cb69-7" tabindex="-1"></a>x[<span class="fu">length</span>(x)] <span class="co">#sidste data point</span></span>
<span id="cb69-8"><a href="baser.html#cb69-8" tabindex="-1"></a><span class="do">## [1] -0.6482168</span></span></code></pre></div>
<p>Bemærk, at i modsætning til Python og mange andre programmeringssprog, bruger R en ‘1’-baseret indeksering. Det betyder, at den første værdi er x[1] og ikke x[0] som i Python.</p>
</div>
<div id="measures-of-central-tendency" class="section level3 hasAnchor" number="1.10.2">
<h3><span class="header-section-number">1.10.2</span> Measures of central tendency<a href="baser.html#measures-of-central-tendency" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<table>
<colgroup>
<col width="50%" />
<col width="50%" />
</colgroup>
<thead>
<tr class="header">
<th>Funktion</th>
<th>Beskrivelse</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>mean()</code></td>
<td>aritmetisk gennemsnit / arithmetic mean <span class="math inline">\(\bar{x}_{i} = \frac{1}{n}\sum_{i=1}^{n} x_{i}\)</span></td>
</tr>
<tr class="even">
<td><code>median()</code></td>
<td>median værdi / median value</td>
</tr>
<tr class="odd">
<td><code>max()</code></td>
<td>maksimum værdi / maximum value</td>
</tr>
<tr class="even">
<td><code>min()</code></td>
<td>minimum værdi / minimum value</td>
</tr>
<tr class="odd">
<td><code>var()</code></td>
<td>varians / variance <span class="math inline">\(s^2 = \frac{1}{n-1}\sum_{i=1}^{n} (x_{i} - \bar{x}_{i})^2\)</span></td>
</tr>
<tr class="even">
<td><code>sd()</code></td>
<td>standardafvigelsen / standard deviation <span class="math inline">\(s\)</span></td>
</tr>
</tbody>
</table>
<p>Lad os afprøve dem på vores simulerede data:</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="baser.html#cb70-1" tabindex="-1"></a>my_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb70-2"><a href="baser.html#cb70-2" tabindex="-1"></a>my_median <span class="ot">&lt;-</span> <span class="fu">median</span>(x)</span>
<span id="cb70-3"><a href="baser.html#cb70-3" tabindex="-1"></a>my_max <span class="ot">&lt;-</span> <span class="fu">max</span>(x)</span>
<span id="cb70-4"><a href="baser.html#cb70-4" tabindex="-1"></a>my_min <span class="ot">&lt;-</span> <span class="fu">min</span>(x)</span>
<span id="cb70-5"><a href="baser.html#cb70-5" tabindex="-1"></a>my_var <span class="ot">&lt;-</span> <span class="fu">var</span>(x)</span>
<span id="cb70-6"><a href="baser.html#cb70-6" tabindex="-1"></a>my_sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(x)</span>
<span id="cb70-7"><a href="baser.html#cb70-7" tabindex="-1"></a><span class="fu">c</span>(my_mean,my_median,my_max,my_min,my_var,my_sd) <span class="co">#print results</span></span></code></pre></div>
<pre><code>## [1]  0.5283319  0.5474202  4.7778033 -1.7885862  1.9101216  1.3820715</code></pre>
<p>Man kan også lave et summary af dataen, som består af mange af de statistiker navnt ovenpå:</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="baser.html#cb72-1" tabindex="-1"></a><span class="fu">summary</span>(x)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## -1.7886 -0.4904  0.5474  0.5283  1.3433  4.7778</code></pre>
</div>
<div id="tapply" class="section level3 hasAnchor" number="1.10.3">
<h3><span class="header-section-number">1.10.3</span> <code>tapply()</code><a href="baser.html#tapply" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><code>tapply()</code> er en meget nyttig funktion i R, som kan bruges til at anvende en funktion på en gruppe af data baseret på værdier i en anden vektor. Funktionen tager tre hovedargumenter: den vektor, som vi ønsker at anvende funktionen på, den vektor, som bruges til at gruppere dataene, og funktionen, som vi ønsker at anvende på hver gruppe. <code>tapply()</code> opdeler dataene i grupper baseret på den anden vektor og anvender funktionen på hver gruppe.</p>
<p>Resultatet af <code>tapply()</code> vil være en vektor, som indeholder resultaterne af funktionen anvendt på hver gruppe af data. For eksempel:</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="baser.html#cb74-1" tabindex="-1"></a><span class="fu">data</span>(iris)</span>
<span id="cb74-2"><a href="baser.html#cb74-2" tabindex="-1"></a><span class="fu">tapply</span>(iris<span class="sc">$</span>Sepal.Length,iris<span class="sc">$</span>Species,mean) <span class="co"># alle argumenter i kun en linje</span></span></code></pre></div>
<pre><code>##     setosa versicolor  virginica 
##      5.006      5.936      6.588</code></pre>
<p>Vi tog en vektor med navn Sepal.Length, opdeler den efter Species og beregner gennemsnittet ved hjælp af funktionen mean for hver af de tre arter i variablen <code>Species</code> (dvs. setosa, versicolor og virginica). Alternativt kunne man have beregnet gennemsnittet for hver af de tre Species separat (en tilgang, der ikke skalerer godt!):</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="baser.html#cb76-1" tabindex="-1"></a><span class="co"># gennemsnit Sepal Length for Species setosa</span></span>
<span id="cb76-2"><a href="baser.html#cb76-2" tabindex="-1"></a>mean_setosa <span class="ot">&lt;-</span> <span class="fu">mean</span>(iris<span class="sc">$</span>Sepal.Length[iris<span class="sc">$</span>Species<span class="sc">==</span><span class="st">&quot;setosa&quot;</span>])</span>
<span id="cb76-3"><a href="baser.html#cb76-3" tabindex="-1"></a></span>
<span id="cb76-4"><a href="baser.html#cb76-4" tabindex="-1"></a><span class="co"># gennemsnit Sepal Length for Species versicolor</span></span>
<span id="cb76-5"><a href="baser.html#cb76-5" tabindex="-1"></a>mean_versi <span class="ot">&lt;-</span> <span class="fu">mean</span>(iris<span class="sc">$</span>Sepal.Length[iris<span class="sc">$</span>Species<span class="sc">==</span><span class="st">&quot;versicolor&quot;</span>]) </span>
<span id="cb76-6"><a href="baser.html#cb76-6" tabindex="-1"></a></span>
<span id="cb76-7"><a href="baser.html#cb76-7" tabindex="-1"></a><span class="co"># gennemsnit Sepal Length for Species virginica</span></span>
<span id="cb76-8"><a href="baser.html#cb76-8" tabindex="-1"></a>mean_virgin <span class="ot">&lt;-</span> <span class="fu">mean</span>(iris<span class="sc">$</span>Sepal.Length[iris<span class="sc">$</span>Species<span class="sc">==</span><span class="st">&quot;virginica&quot;</span>])</span>
<span id="cb76-9"><a href="baser.html#cb76-9" tabindex="-1"></a></span>
<span id="cb76-10"><a href="baser.html#cb76-10" tabindex="-1"></a><span class="fu">c</span>(mean_setosa,mean_versi,mean_virgin)</span></code></pre></div>
<pre><code>## [1] 5.006 5.936 6.588</code></pre>
<p>Det er også værd at kender <code>tapply</code>-koncepten, fordi vi kommer til lære et alternativ i <strong>tidyverse</strong> (dvs. <code>group_by</code> og <code>summarise</code>).</p>
</div>
</div>
<div id="statistike-tester" class="section level2 hasAnchor" number="1.11">
<h2><span class="header-section-number">1.11</span> Statistike tester<a href="baser.html#statistike-tester" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Her er en oversigt over nogle af de mest grundlæggende tests, som man kan udføre på data i R. Vi gå i dybden med teorien bag disse tests (vi håber at du har lært det tidligere), men vi forventer, at du er i stand til at anvende dem korrekt i R og fortolke resultaterne. Hvis du ikke er bekendt med nogle af disse tests, vil der være masser af muligheder for at øve dig i statistik gennem kurset.</p>
<ul>
<li><p>t-test: Bruges til at sammenligne to grupper og afgøre, om forskellen mellem deres gennemsnitlige værdier er statistisk signifikant.</p></li>
<li><p>ANOVA: Bruges til at sammenligne mere end to grupper og afgøre, om der er statistisk signifikant forskel mellem mindst to af grupperne.</p></li>
<li><p>Korrelationsanalyse: Bruges til at afgøre, om der er en statistisk signifikant sammenhæng mellem to variabler.</p></li>
<li><p>Regressionsanalyse: Bruges til at afgøre, om der er en statistisk signifikant sammenhæng mellem en uafhængig variabel og en afhængig variabel. Man forudsige værdien af den afhængige variabel baseret på værdien af den uafhængige variabel.</p></li>
<li><p>Chi-square test: Bruges til at afgøre, om der er en statistisk signifikant forskel mellem observerede og forventede værdier for kategoriske variabler.</p></li>
</ul>
<div id="p-værdien" class="section level3 hasAnchor" number="1.11.1">
<h3><span class="header-section-number">1.11.1</span> P-værdien<a href="baser.html#p-v%C3%A6rdien" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Først og fremmest er det vigtigt at kunne huske p-værdi både i forhold til definitionen og i forhold til hvordan det fortolkes.</p>
<p><strong>P-værdien er sandsynligheden for at observere et resultat lige så ekstremt eller mere ekstremt end det observerede, givet at null-hypotesen er sand</strong>. Null-hypotesen er en antagelse om, at der er ikke en signifikant forskel mellem grupper eller variabler i det dataset, som der arbejdes med.</p>
<p>Hvis p-værdien er mindre end det valgte signifikansniveau (typisk 0,05), så betyder det, at det observerede resultat er usandsynligt at opstå ved ren tilfældighed, og null-hypotesen er afvist til fordel for den alternative hypotese om, at der er en signifikant forskel mellem grupper eller variabler i datasættet.</p>
</div>
<div id="korrelation" class="section level3 hasAnchor" number="1.11.2">
<h3><span class="header-section-number">1.11.2</span> Korrelation<a href="baser.html#korrelation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Korrelation måler styrken og retningen af den lineære sammenhæng mellem to kontinuerte variabler, som begge er normalfordelte:</p>
<ul>
<li><span class="math inline">\(&gt;0\)</span> betyder, at der er en positiv sammenhæng</li>
<li><span class="math inline">\(&lt;0\)</span> betyder, at der er en negativ sammenhæng</li>
<li><span class="math inline">\(=0\)</span> betyder, at der er ingen sammenhængen mellem de to variabler</li>
</ul>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="baser.html#cb78-1" tabindex="-1"></a><span class="fu">data</span>(cars)</span>
<span id="cb78-2"><a href="baser.html#cb78-2" tabindex="-1"></a><span class="fu">cor</span>(cars<span class="sc">$</span>speed, cars<span class="sc">$</span>dist)</span></code></pre></div>
<pre><code>## [1] 0.8068949</code></pre>
<p>Husk dog, at “Correlation does not equal causation” - dvs. at korrelation er bare en sammenhæng og ikke nødvendigvis angiver en årsagssammenhæng mellem to variabler.</p>
<p>Funktionen <code>cor.test()</code> kan bruges til at teste, om korrelationen mellem to variabler er statistisk signifikant. Null-hypotesen antager, at der ikke er nogen korrelation mellem de to variabler i den population som er repræsenteret i datasættet.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="baser.html#cb80-1" tabindex="-1"></a><span class="fu">cor.test</span>(cars<span class="sc">$</span>speed, cars<span class="sc">$</span>dist)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  cars$speed and cars$dist
## t = 9.464, df = 48, p-value = 1.49e-12
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.6816422 0.8862036
## sample estimates:
##       cor 
## 0.8068949</code></pre>
<p>Her er p-værdien 0 mindre end 0.05. Derfor konkluderer man, at der er en signifikant sammenhæng mellem de to variabler.</p>
</div>
<div id="test-for-uafhængighed-chi-sq-test" class="section level3 hasAnchor" number="1.11.3">
<h3><span class="header-section-number">1.11.3</span> Test for uafhængighed (chi-sq test)<a href="baser.html#test-for-uafh%C3%A6ngighed-chi-sq-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En chi-squared test kan bruges til at undersøge, om der er en statistisk signifikant sammenhæng mellem antallet af observationer i to eller flere forskellige kategorier. For eksempel kan man teste for sammenhængen mellem antallet af kopier af en genvariant og to forskellige farver på blomster i en bestemt planteart.</p>
<table>
<thead>
<tr class="header">
<th></th>
<th align="center">0</th>
<th align="center">1</th>
<th align="center">2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>red</td>
<td align="center">29</td>
<td align="center">31</td>
<td align="center">16</td>
</tr>
<tr class="even">
<td>pink</td>
<td align="center">11</td>
<td align="center">16</td>
<td align="center">24</td>
</tr>
</tbody>
</table>
<p>Vi vil gerne vide om phenotypen er afhængig af genotypen:</p>
<ul>
<li><span class="math inline">\(H_{0}:\)</span> antallet af genkopier og phenotypen er uafhængig af hinanden vs</li>
<li><span class="math inline">\(H_{1}:\)</span> antallet af genkopier og phenotypen er afhængig af hinanden</li>
</ul>
<p>Testen antager at man beregner forventede værdier under nulhypotesen som siger at der er ingen sammenhæng mellem de to kategorier. Derefter sammenligner testen disse forventede værdier med de faktiske, observerede værdier. Man laver testen i R ved at benytte funktionen <code>chisq.test()</code>:</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="baser.html#cb82-1" tabindex="-1"></a><span class="fu">chisq.test</span>(dat)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  dat
## X-squared = 9.9516, df = 2, p-value = 0.006903</code></pre>
<p>P-værdien er 0.006903 og mindre end 0.05. Derfor afviser vi nulhypotesen og konkluderer, at der er en signifikant sammenhæng mellem de to variabler. Dette er i overensstemmelse med vores intuition some siger at der er flere røde blomster uden genkopi (0) sammenlignet med røde blomster med to genkopier (2). Det modsatte er sandt for de lyserøde blomster.</p>
</div>
<div id="sample-t-test" class="section level3 hasAnchor" number="1.11.4">
<h3><span class="header-section-number">1.11.4</span> 1 sample t-test<a href="baser.html#sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For at vise en 1-sample t-test, simulerer vi data fra en normalfordeling med middelværdi af 3 ved hjælp af rnorm()-funktionen:</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="baser.html#cb84-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">290223</span>) <span class="co"># bare for at få den samme resultat hver gang</span></span>
<span id="cb84-2"><a href="baser.html#cb84-2" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="at">mean =</span> <span class="dv">3</span>,<span class="at">sd =</span> <span class="dv">1</span>)</span></code></pre></div>
<p>Forestil dig, at du ikke helt stoler på funktionen <code>rnorm()</code> og ønsker at teste, om <code>x</code> stammer fra en normalfordeling med en middelværdi af 3. Nulhypotesen og den alternative hypotese (to-sidet test) er derfor:</p>
<ul>
<li><span class="math inline">\(H_{0}: \mu = 3\)</span>, VS</li>
<li><span class="math inline">\(H_{1}: \mu \neq 3\)</span></li>
</ul>
<p>For at lave testen i R, bruger man funktionen <code>t.test()</code> og angiver <code>mu = 3</code> for at definere vores hypoteser:</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="baser.html#cb85-1" tabindex="-1"></a><span class="fu">t.test</span>(x,<span class="at">mu =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  x
## t = -1.1448, df = 9, p-value = 0.2818
## alternative hypothesis: true mean is not equal to 3
## 95 percent confidence interval:
##  2.169968 3.272231
## sample estimates:
## mean of x 
##  2.721099</code></pre>
<p>Fra resultatet kan man se, at p-værdien er estimeret til 0.2818, og da den er større end 0.05 kan vi ikke afvise nulhypotesen. Derfor kan vi konkluderer at middelværdien af x ikke adskiller sig signifikant fra 3.</p>
<p><strong>Bemærkning</strong>: da vi simulerede vores data fra en normalfordeling med en middelværdi af tre, vidste vi i forvejen at det korrekte svar er, at acceptere nullhypotesen. Hvis vi ville have afvist nullhypotesen, ville vi have lavet en <strong>type I fejl</strong> - dvs. at vi afviser nullhypotesen når det faktisk er sandt.</p>
</div>
<div id="sample-t-test-1" class="section level3 hasAnchor" number="1.11.5">
<h3><span class="header-section-number">1.11.5</span> 2-sample t-test<a href="baser.html#sample-t-test-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Undersøger om der er en forskel mellem middelværdierne af to grupper - er disse grupper afledt af den samme normalfordeling? Hypoteserne er således (to-sidet):</p>
<ul>
<li><span class="math inline">\(H_{0}: \mu_{1} = \mu_{2}\)</span>, VS</li>
<li><span class="math inline">\(H_{1}: \mu_{1} \neq \mu_{2}\)</span></li>
</ul>
<p>I følgende kode simulere vi to stikprøver, der kommer fra en normalfordeling med forskellige middelværdier og bruger funktionen <code>t.test</code>. Man kan definere at de to stikprøver har samme varians ved <code>var.equal = T</code> indenfor funktionen <code>t.test</code>:</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="baser.html#cb87-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">3</span>,<span class="dv">1</span>)</span>
<span id="cb87-2"><a href="baser.html#cb87-2" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">5</span>,<span class="dv">1</span>)</span>
<span id="cb87-3"><a href="baser.html#cb87-3" tabindex="-1"></a></span>
<span id="cb87-4"><a href="baser.html#cb87-4" tabindex="-1"></a><span class="fu">t.test</span>(x,y,<span class="at">var.equal =</span> T)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  x and y
## t = -5.4258, df = 18, p-value = 3.729e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2.700858 -1.193081
## sample estimates:
## mean of x mean of y 
##  2.783056  4.730025</code></pre>
<p>Hvis man til gengæld ikke kan antage, at variansen er den samme i de to grupper:</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="baser.html#cb89-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="dv">3</span>, <span class="dv">1</span>)</span>
<span id="cb89-2"><a href="baser.html#cb89-2" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="dv">5</span>, <span class="dv">3</span>) <span class="co">#større variance</span></span>
<span id="cb89-3"><a href="baser.html#cb89-3" tabindex="-1"></a></span>
<span id="cb89-4"><a href="baser.html#cb89-4" tabindex="-1"></a><span class="fu">t.test</span>(x,y,<span class="at">var.equal =</span> F) <span class="co">#var.equal=F er &#39;default&#39; så man behøver ikke at specifere</span></span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  x and y
## t = -2.0238, df = 11.77, p-value = 0.0663
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -3.9077927  0.1483728
## sample estimates:
## mean of x mean of y 
##  2.757436  4.637146</code></pre>
<p>Bemærk at hvis man kan antage at variansen er den samme, så har man mere <strong>power</strong> (kræft) til at opdage en virkelig forskel (dvs. få en signifikant forskel som resultat af testen).</p>
</div>
<div id="paired-t-test-parret-t-test" class="section level3 hasAnchor" number="1.11.6">
<h3><span class="header-section-number">1.11.6</span> Paired t-test / parret t-test<a href="baser.html#paired-t-test-parret-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En parret t-test anvender man f.eks. når man har målinger af den samme population af personer i hver stikprøve, og man gerne vil teste om forskellen i værdier mellem de to stikprøver er signifikant. For eksempel hvis vi har “før” og “efter” målinger af de samme 10 personer:</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="baser.html#cb91-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">320</span>)</span>
<span id="cb91-2"><a href="baser.html#cb91-2" tabindex="-1"></a>before <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="dv">3</span>, <span class="dv">1</span>)</span>
<span id="cb91-3"><a href="baser.html#cb91-3" tabindex="-1"></a>after <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="dv">6</span>, <span class="dv">2</span>)</span>
<span id="cb91-4"><a href="baser.html#cb91-4" tabindex="-1"></a></span>
<span id="cb91-5"><a href="baser.html#cb91-5" tabindex="-1"></a><span class="fu">t.test</span>(before, after, <span class="at">paired =</span> T) <span class="co"># definere parret data</span></span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  before and after
## t = -9.3296, df = 9, p-value = 6.356e-06
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  -5.415186 -3.301613
## sample estimates:
## mean difference 
##       -4.358399</code></pre>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="baser.html#cb93-1" tabindex="-1"></a><span class="fu">t.test</span>(before <span class="sc">-</span> after, <span class="at">mu =</span> <span class="dv">0</span>) <span class="co"># exactly the same result</span></span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  before - after
## t = -9.3296, df = 9, p-value = 6.356e-06
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -5.415186 -3.301613
## sample estimates:
## mean of x 
## -4.358399</code></pre>
</div>
<div id="anova-variansanalyse" class="section level3 hasAnchor" number="1.11.7">
<h3><span class="header-section-number">1.11.7</span> ANOVA (variansanalyse)<a href="baser.html#anova-variansanalyse" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Har man flere grupper i stedet for to, kan man bruge ANOVA (analysis of variance eller variansanalyse). Har man en kategorisk variabel med <span class="math inline">\(k\)</span> grupper, er nul/alternativhypotesen:</p>
<ul>
<li><span class="math inline">\(H_{0}: \mu_{1} = \mu_{2} = \ldots = \mu_{k}\)</span></li>
<li><span class="math inline">\(H_{1}:\)</span> ikke alle middelværdier er ens</li>
</ul>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="baser.html#cb95-1" tabindex="-1"></a><span class="co">#simulere data til 3 forskellige grupper fra den normalfordeling med standardafvigelse af 3</span></span>
<span id="cb95-2"><a href="baser.html#cb95-2" tabindex="-1"></a>group1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">50</span>, <span class="dv">10</span>, <span class="dv">3</span>)</span>
<span id="cb95-3"><a href="baser.html#cb95-3" tabindex="-1"></a>group2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">55</span>, <span class="dv">10</span>, <span class="dv">3</span>)</span>
<span id="cb95-4"><a href="baser.html#cb95-4" tabindex="-1"></a>group3 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">48</span>, <span class="dv">5</span>, <span class="dv">3</span>)</span>
<span id="cb95-5"><a href="baser.html#cb95-5" tabindex="-1"></a></span>
<span id="cb95-6"><a href="baser.html#cb95-6" tabindex="-1"></a><span class="co">#data må være i en dataramme, med vores værdier i den ene kolonne og grupperne i den anden kolonne</span></span>
<span id="cb95-7"><a href="baser.html#cb95-7" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(group1, group2, group3)</span>
<span id="cb95-8"><a href="baser.html#cb95-8" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;G1&quot;</span>,<span class="dv">50</span>), <span class="fu">rep</span>(<span class="st">&quot;G2&quot;</span>,<span class="dv">55</span>), <span class="fu">rep</span>(<span class="st">&quot;G3&quot;</span>,<span class="dv">48</span>))</span>
<span id="cb95-9"><a href="baser.html#cb95-9" tabindex="-1"></a>mydf <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="st">&quot;group&quot;</span> <span class="ot">=</span> x, <span class="st">&quot;value&quot;</span> <span class="ot">=</span> y)</span></code></pre></div>
<p>For at udføre testen kan man anvende funktionen <code>lm()</code>, som står for “linear model” og kan bruges til at opbygge forskellige modeller. Her definerer vi en model, hvor hver gruppe (<code>G1</code>, <code>G2</code> og <code>G3</code> fra variablen <code>x</code>) har sin egen middelværdi. Forskellen mellem disse middelværdier udgør definitionen af vores alternativhypotesen:</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="baser.html#cb96-1" tabindex="-1"></a>mylm <span class="ot">&lt;-</span> <span class="fu">lm</span>(value <span class="sc">~</span> group, <span class="at">data =</span> mydf) <span class="co">#H1 model</span></span></code></pre></div>
<p>Under nulhypotesen til gengæld har alle grupper den samme middelværdi, og derfor behøver vi ikke at inkludere variablen <code>group</code> i modellen. Vi definerer det i modellen ved at skrive 1, som betyder, at forventede værdier for den afhængige variabel <code>value</code> blot er dens middelværdi:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="baser.html#cb97-1" tabindex="-1"></a>mylm_null <span class="ot">&lt;-</span> <span class="fu">lm</span>(value <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> mydf) <span class="co">#H0 model</span></span></code></pre></div>
<p>For at sammenligne de to modeller benytter vi funktionen <code>anova()</code> (efter analysis of variance):</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="baser.html#cb98-1" tabindex="-1"></a><span class="fu">anova</span>(mylm_null, mylm)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: value ~ 1
## Model 2: value ~ group
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    152 2215.4                                  
## 2    150 1509.9  2    705.55 35.047 3.245e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>P-værdien er (&lt;0.05). Nulhypotesen er afvist til fordel for alternativhypotesen, altså modellen, hvor hver gruppe har sin egen middelværdi. OBS! Det er på trods af, at to af tre grupper kommer fra en normalfordeling med præcis de samme middelværdier. Faktisk er det nok at den trejde gruppe har en anden middelværdi.</p>
<!-- * Grupper må være normale fordelt -->
<!-- * Variancen må være de samme i alle grupper -->
</div>
<div id="lineær-regression-linear-regression" class="section level3 hasAnchor" number="1.11.8">
<h3><span class="header-section-number">1.11.8</span> Lineær regression / linear regression<a href="baser.html#line%C3%A6r-regression-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><em>OBS! Se også venligst videon vedrørende R Markdown (næste emne), hvor Sarah arbejder igennem lineær regression med R.</em></p>
<p>Formålet af en lineær regression er at måle (en retningsbestemt) relation mellem to kontinuerte variabler. I simpel lineær regression svarer det til, at man vil finde den rette linje gennem punkterne, der bedst beskriver relationen.</p>
<p>Som en eksempel anvender vi datasættet <code>mtcars</code> og definere den afhængige (response) variabel via <code>mpg</code> og den uafhængige (predictor) variabel som <code>wt</code>.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-60-1.png" width="480" /></p>
<p>Som beskrevet tidligere, skriver vi relationer i R som f.eks. <code>mpg ~ wt</code> og benytter <code>lm()</code>(<code>lm(mpg~wt,data=mtcars)</code>):</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="baser.html#cb100-1" tabindex="-1"></a>mylm <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt, <span class="at">data =</span> mtcars)  <span class="co"># opbyg en lineær regressions model</span></span>
<span id="cb100-2"><a href="baser.html#cb100-2" tabindex="-1"></a>mylm</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt, data = mtcars)
## 
## Coefficients:
## (Intercept)           wt  
##      37.285       -5.344</code></pre>
<p>Vores koefficienter / coefficients beskriver den bedste rette linje:</p>
<ul>
<li>Skæringen (intercept): 37.285</li>
<li>Hældningskoefficient (slope): -5.344</li>
</ul>
<p>Det betyder, at hvis vægten <code>wt</code> af en bil stiger med 1, så stiger <code>mpg</code> ved -5.344 (det vil sige at <code>mpg</code> reduceres med 5.344).</p>
</div>
<div id="r-squared-bestemmelseskoefficient-koefficient-of-determination" class="section level3 hasAnchor" number="1.11.9">
<h3><span class="header-section-number">1.11.9</span> R-squared bestemmelseskoefficient / koefficient of determination<a href="baser.html#r-squared-bestemmelseskoefficient-koefficient-of-determination" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><span class="math inline">\(R^2\)</span> eller “forklaringsgraden” (bestemmelseskoefficient) har til formål at forklare, hvor godt vores lineær model passer til de data. For eksempel hvor meget af variansen i <code>mpg</code> forklares af variablen <code>wt</code>?</p>
<ul>
<li>Hvis det er tæt på 1 - så er der en meget tæt relation (hvis man kender vægten, så vide man også <code>mpg</code> med stor sikkerhed).</li>
<li>Hvis det er tæt på 0 - så er relationen svag - sandsynligheden er høj at der er andre variabler der bedre forklarer variansen i <code>mpg</code>.</li>
</ul>
<p>I ovenstående model, kan man se <span class="math inline">\(R^2\)</span> værdien med <code>summary(mylm)</code>.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="baser.html#cb102-1" tabindex="-1"></a><span class="fu">summary</span>(mylm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.5432 -2.3647 -0.1252  1.4096  6.8727 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  37.2851     1.8776  19.858  &lt; 2e-16 ***
## wt           -5.3445     0.5591  -9.559 1.29e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.046 on 30 degrees of freedom
## Multiple R-squared:  0.7528, Adjusted R-squared:  0.7446 
## F-statistic: 91.38 on 1 and 30 DF,  p-value: 1.294e-10</code></pre>
<p>Det fortæller os, at <span class="math inline">\(R^2\)</span> = 0.7528.</p>
</div>
<div id="antagelser-ved-brug-af-lineær-regression" class="section level3 hasAnchor" number="1.11.10">
<h3><span class="header-section-number">1.11.10</span> Antagelser ved brug af lineær regression<a href="baser.html#antagelser-ved-brug-af-line%C3%A6r-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Normalfordelte residualer</li>
<li>Residualer har samme spredning (varianshomogenitet)</li>
<li>Uafhængighed</li>
<li>Fit er linæer</li>
</ul>
<p>Koden <code>plot(mylm,which=c(1))</code> beskriver residualer vs forudsagte (fitted) værdier - de skal være tilfældigt fordelt over plottet og prikkernes varians skal være nogenlunde konstant langt x-aksen (dette afspejles i den flade forløb af den røde linje).</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="baser.html#cb104-1" tabindex="-1"></a><span class="fu">plot</span>(mylm, <span class="at">which =</span> <span class="fu">c</span>(<span class="dv">1</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-63-1.png" width="480" /></p>
<p>Med koden <code>plot(mylm, which = c(2))</code> kan man tjekke antagelsen af en normalfordeling. Punkterne skal være nogenlunde tæt på den diagonale linje.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="baser.html#cb105-1" tabindex="-1"></a><span class="fu">plot</span>(mylm, <span class="at">which =</span> <span class="fu">c</span>(<span class="dv">2</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-64-1.png" width="480" /></p>
</div>
<div id="multiple-lineær-regression" class="section level3 hasAnchor" number="1.11.11">
<h3><span class="header-section-number">1.11.11</span> Multiple lineær regression<a href="baser.html#multiple-line%C3%A6r-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Her kan man tilføje flere variabler til formlen af vores model.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="baser.html#cb106-1" tabindex="-1"></a>mylm_disp <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt <span class="sc">+</span> disp, <span class="at">data =</span> mtcars) <span class="co"># opbyg en lineær regressions model</span></span>
<span id="cb106-2"><a href="baser.html#cb106-2" tabindex="-1"></a><span class="fu">summary</span>(mylm_disp)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt + disp, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.4087 -2.3243 -0.7683  1.7721  6.3484 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 34.96055    2.16454  16.151 4.91e-16 ***
## wt          -3.35082    1.16413  -2.878  0.00743 ** 
## disp        -0.01773    0.00919  -1.929  0.06362 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.917 on 29 degrees of freedom
## Multiple R-squared:  0.7809, Adjusted R-squared:  0.7658 
## F-statistic: 51.69 on 2 and 29 DF,  p-value: 2.744e-10</code></pre>
<p>Her kan man se, at med tilføjelsen af variablen <code>disp</code>, er <span class="math inline">\(R^2\)</span> steget til 0.7809. Bemærk, at jo flere variabler man tilføjer til modellen, jo større bliver <span class="math inline">\(R^2\)</span>-værdien. Den modificeret <span class="math inline">\(R^2\)</span> værdi er lavere fordi den prøver at tage højde for kompleksiteten af modellen (mængden af parametre der er).</p>
<p>Variablen <code>disp</code> er faktisk ikke selv signifikant når der er taget højde for variablen <code>wt</code> (p-værdien 0.0636 - tjek, at du selv kan finde værdien i resultatet).</p>
<p>Hvis en af de uafhængige variabler er kategorisk, bruger man funktionen <code>anova</code> til at teste effekten af den variabel. For eksempel har variablen <code>cyl</code> 3 mulige værdier (niveauer) - 4, 6 og 8. Vi kan tage op variablen i vores model:</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="baser.html#cb108-1" tabindex="-1"></a>mylm_cyl <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt <span class="sc">+</span> <span class="fu">factor</span>(cyl), <span class="at">data =</span> mtcars)</span>
<span id="cb108-2"><a href="baser.html#cb108-2" tabindex="-1"></a><span class="fu">summary</span>(mylm_cyl)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt + factor(cyl), data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.5890 -1.2357 -0.5159  1.3845  5.7915 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   33.9908     1.8878  18.006  &lt; 2e-16 ***
## wt            -3.2056     0.7539  -4.252 0.000213 ***
## factor(cyl)6  -4.2556     1.3861  -3.070 0.004718 ** 
## factor(cyl)8  -6.0709     1.6523  -3.674 0.000999 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.557 on 28 degrees of freedom
## Multiple R-squared:  0.8374, Adjusted R-squared:   0.82 
## F-statistic: 48.08 on 3 and 28 DF,  p-value: 3.594e-11</code></pre>
<!-- Der er faktisk tre rette linjer her - en for hvert niveau af `cyl`, og de har samme hældning med forskellige skæringspunkter. -->
<!-- * Hvis `cyl = 4`: mpg $= 33.99 - 3.21$wt -->
<!-- * Hvis `cyl = 6`: mpg $= 33.99 - 3.21$wt $-4.26$ -->
<!-- * Hvis `cyl = 8`: mpg $= 33.99 - 3.21$wt $-6.07$ -->
<p>Man kan ikke se effekten af <code>cyl</code> i den ovenstående <code>summary</code> men man kan teste den med <code>anova</code>:</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="baser.html#cb110-1" tabindex="-1"></a><span class="fu">anova</span>(mylm,mylm_cyl)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: mpg ~ wt
## Model 2: mpg ~ wt + factor(cyl)
##   Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)   
## 1     30 278.32                                
## 2     28 183.06  2    95.263 7.2856 0.002835 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Så kan man se, at <code>cyl</code> er signifikant.</p>
</div>
</div>
<div id="problemstillinger" class="section level2 hasAnchor" number="1.12">
<h2><span class="header-section-number">1.12</span> Problemstillinger<a href="baser.html#problemstillinger" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Husk quizzen på Absalon, og lav gerne nedenstående øvelser for at øve dine færdigheder i R:</p>
<ul>
<li>Øvelser 2-8 er meget grundlæggende og kan godt springes over, hvis man er nogenlunde fortrolig med base-R.</li>
<li>Vi vil anbefale øvelser 9-15 til alle som en god måde at teste jeres viden.</li>
<li>Øvelser 16-20 fokuserer på andre statistiske tests i R. Vi kommer tilbage til regression flere gange i kurset, så det vil være en god idé at have kendskab til funktionen <code>lm()</code> til at opbygge modeller i ANOVA / simpel lineær regression (se også videoen og problemstillingerne knyttet til det næste emne, R Markdown).</li>
</ul>
<div id="quiz---basics" class="section level3 hasAnchor" number="1.12.1">
<h3><span class="header-section-number">1.12.1</span> Quiz - Basics<a href="baser.html#quiz---basics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>1)</strong> Lav venligst quizzen på Absalon som hedder “Quiz - Grundlæggende”.</p>
</div>
<div id="grundlæggende-r" class="section level3 hasAnchor" number="1.12.2">
<h3><span class="header-section-number">1.12.2</span> Grundlæggende R<a href="baser.html#grundl%C3%A6ggende-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>2)</strong> (<strong>helt grundlæggende viden</strong>)</p>
<p>Åbn en ny fil i RStudio ved at klikke på “File” &gt; “New File” &gt; “R Script”. Kør følgende kode en linje ad gangen og tjek, om du forstår outputtet.</p>
<p>Husk, at den nemmeste måde at køre kode på er ved at trykke på CMD+ENTER (Mac) eller WIN-KEY+ENTER (Windows).</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="baser.html#cb112-1" tabindex="-1"></a><span class="dv">2</span><span class="sc">+</span><span class="dv">2</span></span>
<span id="cb112-2"><a href="baser.html#cb112-2" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="dv">2</span></span>
<span id="cb112-3"><a href="baser.html#cb112-3" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb112-4"><a href="baser.html#cb112-4" tabindex="-1"></a>x <span class="ot">&lt;-</span> x<span class="sc">+</span><span class="dv">2</span></span>
<span id="cb112-5"><a href="baser.html#cb112-5" tabindex="-1"></a><span class="fu">sqrt</span>(x)</span>
<span id="cb112-6"><a href="baser.html#cb112-6" tabindex="-1"></a><span class="fu">sqrt</span>(x)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb112-7"><a href="baser.html#cb112-7" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="dv">2</span>, <span class="dv">2</span>)</span>
<span id="cb112-8"><a href="baser.html#cb112-8" tabindex="-1"></a><span class="fu">log10</span>(<span class="dv">100</span>)</span>
<span id="cb112-9"><a href="baser.html#cb112-9" tabindex="-1"></a>y <span class="ot">&lt;-</span>  <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">4</span>, <span class="dv">3</span>)</span>
<span id="cb112-10"><a href="baser.html#cb112-10" tabindex="-1"></a><span class="fu">class</span>(y)</span>
<span id="cb112-11"><a href="baser.html#cb112-11" tabindex="-1"></a><span class="fu">class</span>(<span class="fu">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;b&quot;</span>, <span class="st">&quot;c&quot;</span>))</span>
<span id="cb112-12"><a href="baser.html#cb112-12" tabindex="-1"></a><span class="fu">mean</span>(y)</span>
<span id="cb112-13"><a href="baser.html#cb112-13" tabindex="-1"></a><span class="fu">sd</span>(y)</span>
<span id="cb112-14"><a href="baser.html#cb112-14" tabindex="-1"></a><span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">13</span>, <span class="at">by =</span> <span class="dv">3</span>)</span></code></pre></div>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="baser.html#cb113-1" tabindex="-1"></a><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>) <span class="sc">&gt;</span> <span class="dv">2</span> <span class="co">#giver bare TRUE eller FALSE</span></span>
<span id="cb113-2"><a href="baser.html#cb113-2" tabindex="-1"></a><span class="fu">ifelse</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>) <span class="sc">&gt;</span> <span class="dv">2</span>, <span class="st">&quot;yes&quot;</span>, <span class="st">&quot;no&quot;</span>) <span class="co">#omsætte TRUE eller FALSE til &quot;yes&quot; eller &quot;no&quot;</span></span>
<span id="cb113-3"><a href="baser.html#cb113-3" tabindex="-1"></a><span class="fu">ifelse</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>) <span class="sc">&gt;=</span> <span class="dv">2</span>, <span class="st">&quot;yes&quot;</span>, <span class="st">&quot;no&quot;</span>) <span class="co">#se forskellen</span></span>
<span id="cb113-4"><a href="baser.html#cb113-4" tabindex="-1"></a><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>) <span class="sc">==</span> <span class="dv">2</span> <span class="co">#logic</span></span>
<span id="cb113-5"><a href="baser.html#cb113-5" tabindex="-1"></a><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>) <span class="sc">!=</span> <span class="dv">2</span> <span class="co">#logic</span></span></code></pre></div>
<p><strong>3)</strong> (<strong>helt grundlæggende viden</strong>)</p>
<p>Kør følgende kode for at åbne nogle af de indbyggede datasæt, som vi også kommer til at bruge i kurset.</p>
<ul>
<li>Prøve <code>head()</code>, <code>nrow()</code>, <code>summary()</code> osv.</li>
<li>Prøve også f.eks. <code>?cars</code> for at se en beskrivelse.</li>
</ul>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="baser.html#cb114-1" tabindex="-1"></a><span class="fu">data</span>(iris)</span>
<span id="cb114-2"><a href="baser.html#cb114-2" tabindex="-1"></a><span class="fu">data</span>(cars)</span>
<span id="cb114-3"><a href="baser.html#cb114-3" tabindex="-1"></a><span class="fu">data</span>(ToothGrowth)</span>
<span id="cb114-4"><a href="baser.html#cb114-4" tabindex="-1"></a><span class="fu">data</span>(sleep)</span>
<span id="cb114-5"><a href="baser.html#cb114-5" tabindex="-1"></a><span class="fu">head</span>(chickwts)</span>
<span id="cb114-6"><a href="baser.html#cb114-6" tabindex="-1"></a><span class="fu">data</span>(trees)</span>
<span id="cb114-7"><a href="baser.html#cb114-7" tabindex="-1"></a><span class="co">#se her for andre:</span></span>
<span id="cb114-8"><a href="baser.html#cb114-8" tabindex="-1"></a><span class="fu">library</span>(<span class="at">help =</span> <span class="st">&quot;datasets&quot;</span>)</span></code></pre></div>
<p><strong>4)</strong> (<strong>grundlæggende plots</strong>)</p>
<p>Vi viser eksempler for at plotte datasættet “iris”. Prøv også at plotte data af andre indbyggede datasæt, som du har indlæst.</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="baser.html#cb115-1" tabindex="-1"></a><span class="fu">plot</span>(iris<span class="sc">$</span>Sepal.Length,iris<span class="sc">$</span>Sepal.Width)</span>
<span id="cb115-2"><a href="baser.html#cb115-2" tabindex="-1"></a><span class="fu">hist</span>(iris<span class="sc">$</span>Sepal.Width)</span>
<span id="cb115-3"><a href="baser.html#cb115-3" tabindex="-1"></a><span class="fu">boxplot</span>(iris<span class="sc">$</span>Sepal.Length<span class="sc">~</span>iris<span class="sc">$</span>Species)</span></code></pre></div>
<p>Du kan også gøre plottene mere informativ ved at give dem en titel og navne på akserne. Prøv at finde dokumentationen for plot() ved at skrive <code>?plot</code> i R-konsollen. Du kan tilføje <code>ylab</code>, <code>xlab</code> og <code>main</code> (titel) i én af plottene. Prøv også at eksperimentere med farver ved at bruge <code>col</code>. Bemærk dog, at vi vil skifte måden at lave plottene, når vi begynder at bruge <code>ggplot2</code>.</p>
<p><strong>5)</strong> (<strong>dataframes</strong>)</p>
<p>Brug datasættet <code>cars</code> (<code>data(cars)</code>) til at:</p>
<ul>
<li>Lav et scatter plot med <code>speed</code> på x-aksen og <code>dist</code> på y-aksen.</li>
<li>Tilføj en ny kolonne med følgende kode:</li>
</ul>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="baser.html#cb116-1" tabindex="-1"></a>cars<span class="sc">$</span>fast <span class="ot">&lt;-</span> cars<span class="sc">$</span>speed <span class="sc">&gt;</span> <span class="dv">15</span></span></code></pre></div>
<ul>
<li>Brug <code>mean</code> på den nye kolonne <code>fast</code> for at finde ud af andelen af biler, der er hurtige end 15.</li>
<li>Brug <code>ifelse</code> så at du får <code>fast</code> eller <code>slow</code> i din nye kolonne i stedet for TRUE/FALSE.</li>
<li>Beregn gennemsnitsværdien af variablen <code>dist</code> for <code>fast</code> biler og <code>slow</code> biler hver for sig (brug funktionen <code>tapply</code>). Gem resultatet med <code>&lt;-</code>.</li>
<li>Brug <code>barplot</code> til at lave et plot af den gennemsnitlige <code>dist</code> for <code>fast</code> biler og <code>slow</code> biler.</li>
</ul>
<p><strong>6)</strong> (<strong>dataframes</strong>)</p>
<p>En dataframe kan indeholde forskellige datatyper (i modsætning til en matrix). Lav en ny dataframe (med funktionen <code>data.frame()</code>) med tre kolonner, som hedder <code>navn</code>, <code>alder</code> og <code>yndlings_farve</code> (vælg værdierne selv). Sørg for, at din dataframe har 4 rækker.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="baser.html#cb117-1" tabindex="-1"></a>mydf <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="st">&quot;navn&quot;</span><span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;alice&quot;</span>,<span class="st">&quot;freddy&quot;</span>, ... ), <span class="st">&quot;alder&quot;</span> <span class="ot">=</span> <span class="fu">c</span>(...), ...) <span class="co"># OBS! Tilpasse venlisgt og fjern &quot;...&quot;</span></span>
<span id="cb117-2"><a href="baser.html#cb117-2" tabindex="-1"></a><span class="fu">dim</span>(mydf) <span class="co"># fire rækker og tre kolonner</span></span>
<span id="cb117-3"><a href="baser.html#cb117-3" tabindex="-1"></a>mydf</span></code></pre></div>
<p><strong>7)</strong> (<strong>dataframes</strong>)</p>
<ul>
<li>Tilføj en ny kolonne <code>random</code> til din egen dataframe - hvor værdierne kommer fra en normalfordeling med en middelværdi af 5 og standardafvigelsen af 1 (bruge venligst funktionen <code>rnorm()</code>).</li>
</ul>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="baser.html#cb118-1" tabindex="-1"></a>mydf<span class="sc">$</span>random <span class="ot">&lt;-</span> <span class="co"># skriv her</span></span></code></pre></div>
<ul>
<li>Tilføj endnu en kolonne, <code>lucky_number</code>, til din dataframe ved at bruge funktionen <code>sample()</code> for at tilføje et tilfældigt tal mellem 1 og 4 (prøv også <code>replace=TRUE</code> og <code>replace=FALSE</code> og forstå forskellen)</li>
</ul>
<!-- 5) (**dataframes**) Lav en `data.frame` (dataframe) med to kolonner og 12 observationer. Den ene varible skal være tilfældige data fra en normal fordeling (bruge funktionen `rnorm`) med et gennemsnit på 5 og varians på 1, den anden variable skal veksle mellem "blue" og "red" (bruge `rep(c("blue","red","yellow"),4)`). -->
<!-- ```{r,eval=F} -->
<!-- set.seed(83902) #some seed so everyone's result is the same -->
<!-- mydf <- data.frame("value"= rnorm(12,5,1), "colour" = rep(c("blue","red","yellow"),4)) -->
<!-- dim(mydf) #otte rækker og tre kolonner -->
<!-- mydf -->
<!-- ``` -->
<p><strong>8)</strong> (<strong>delmængder af dataframes</strong>)</p>
<p>Åbn datasættet “ToothGrowth” med følgende kode:</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="baser.html#cb119-1" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;ToothGrowth&quot;</span>)</span>
<span id="cb119-2"><a href="baser.html#cb119-2" tabindex="-1"></a>?ToothGrowth</span></code></pre></div>
<ul>
<li>Find delmængden af datasættet så at diet (variablen <code>supp</code>) er “OJ” og længden (variablen <code>len</code>) er større end 15.</li>
</ul>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="baser.html#cb120-1" tabindex="-1"></a>newdf <span class="ot">&lt;-</span> ToothGrowth[<span class="co">#skriv venligst her og lave delmængden af observationerne,]</span></span></code></pre></div>
<ul>
<li>Hvor mange rækker er der i den nye dataramme <code>newdf</code>?</li>
<li>Hvor mange unikke værdier er der i variablen <code>dose</code> (brug funktionen <code>unique</code>) ?</li>
<li>Find delmængden af datasættet <code>ToothGrowth</code>, hvor variablen <code>dose</code> er 0.5 eller 2.0 (hint: brug <code>%in%</code> eller <code>|</code>) og <code>supp</code> er “VC”.</li>
<li>Beregn den gennemsnitlige længde for observationerne i delmængden.</li>
</ul>
</div>
<div id="kort-analyse-med-reaktionstider" class="section level3 hasAnchor" number="1.12.3">
<h3><span class="header-section-number">1.12.3</span> Kort analyse med reaktionstider<a href="baser.html#kort-analyse-med-reaktionstider" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>9)</strong> (<strong>indlæse data</strong>)</p>
<p>Åbn filen “reactions.txt” (se Absalon) ved at bruge funktionen <code>read.table()</code> og gem resultatet i variablen <code>data</code>. Husk at tjekke, om filen indeholder variabelnavne og brug <code>header=T</code> hvis nødvendigt.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="baser.html#cb121-1" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="co"># skriv her</span></span></code></pre></div>
<p><strong>10)</strong> (<strong>faktor variabler</strong>)</p>
<p>Variablerne <code>subject</code> og <code>time</code> blev indlæst som henholdsvis <strong>int</strong> (heltal) og <strong>chr</strong> (character) datatyper, men de skal i stedet være <strong>factor</strong> variabler. Brug funktionen <code>as.factor()</code> til at ændre dem til at være <code>factor</code> variabler.</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="baser.html#cb122-1" tabindex="-1"></a><span class="co">#gør subject til en faktor</span></span>
<span id="cb122-2"><a href="baser.html#cb122-2" tabindex="-1"></a>data<span class="sc">$</span>subject <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>subject) </span>
<span id="cb122-3"><a href="baser.html#cb122-3" tabindex="-1"></a></span>
<span id="cb122-4"><a href="baser.html#cb122-4" tabindex="-1"></a><span class="do">## gør den samme her for time:</span></span></code></pre></div>
<ul>
<li>Hvor mange niveauer er der i hver af de to variabler efter ændringen til faktorvariabler? Prøv funktionerne <code>levels()</code> eller <code>nlevels()</code>.</li>
</ul>
<p><strong>11)</strong> (<strong>delmængder af dataframes</strong>)</p>
<p>Lav to delmængder af det ovenstående datasæt ved at:</p>
<ul>
<li>Oprette en delmængde til alle observationer fra tidspunktet “før” ved at vælge rækkerne i dataframen hvor data$time == “before”.</li>
<li>Oprette en delmængde til alle observationer fra tidspunktet “efter”.</li>
</ul>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="baser.html#cb123-1" tabindex="-1"></a>RT_before <span class="ot">&lt;-</span> data[ <span class="co"># skriv her , ]</span></span>
<span id="cb123-2"><a href="baser.html#cb123-2" tabindex="-1"></a>RT_after <span class="ot">&lt;-</span> <span class="co"># skriv her</span></span></code></pre></div>
<ul>
<li>Opret endu en delmængde, som viser alle observationer fra tidspunktet “før” med en reaktionstid på mindst 800.</li>
<li>Hvor mange personer er der i denne delmængde?</li>
</ul>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="baser.html#cb124-1" tabindex="-1"></a>RT_before_mindst800 <span class="ot">&lt;-</span> <span class="co"># skriv her</span></span></code></pre></div>
<p><strong>12)</strong> (<strong>mean og tapply</strong>)</p>
<p>Benyt funktionen <code>mean()</code> til at beregne den gennemsnitlige reaktionstid (variablen <code>RT</code>) for “before”- og “after”-delmængderne.</p>
<ul>
<li>Brug funktionen <code>tapply()</code> på det oprindelige datasæt <code>data</code> for at beregne den samme middelværdi med mindre kode.</li>
</ul>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="baser.html#cb125-1" tabindex="-1"></a><span class="fu">tapply</span>(<span class="co">#skrive her,#skrive her,#skrive her)</span></span></code></pre></div>
<ul>
<li>Er reaktionstiderne blevet hurtigere eller langsommere i gennemsnit?</li>
</ul>
<p><strong>13)</strong> (<strong>beregn forskellen og genemmsnittet</strong>)</p>
<p>Bemærk, at datasættet er ‘paired’ - målingerne er fra de samme personer både “before” og “after”.</p>
<ul>
<li>Opret en vektor <code>diff</code>, der indeholder forskellene i reaktionstiderne mellem “before” og “after” for hver person.</li>
<li>Beregn venligst den gennemsnitlige forskel i rekationstiderne.</li>
</ul>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="baser.html#cb126-1" tabindex="-1"></a>diff <span class="ot">&lt;-</span> <span class="co"># ændringen i reaktionstiden mellem &quot;before&quot; and &quot;after&quot;</span></span>
<span id="cb126-2"><a href="baser.html#cb126-2" tabindex="-1"></a><span class="fu">mean</span>(diff)</span></code></pre></div>
<ul>
<li>Tjek, om tegnet på middelværdien stemmer overens med din konklusion fra <strong>11)</strong> - hvis den er positiv, betyder det, at reaktionstiderne er blevet langsommere.</li>
</ul>
<p><strong>14)</strong> (<strong>lav t-test i R</strong>)</p>
<p>Lav en t-test (funktionen <code>t.test()</code>) for at teste hypotesen om, at den gennemsnitslige forskel i reaktionstiderne mellem “before” og “after” er forskellige fra 0.</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="baser.html#cb127-1" tabindex="-1"></a><span class="fu">t.test</span>(<span class="co">#skrive her..)</span></span></code></pre></div>
<p>Find følgende i outputtet fra R:</p>
<ul>
<li>Hvor er test-statistiken <code>t</code>?</li>
<li>Hvor er p-værdien?</li>
<li>Hvad er alternativhypotesen?</li>
</ul>
<p>Husk at skrive en kort sætning med dine endelige konklusioner.</p>
</div>
<div id="øvelse-med-co2" class="section level3 hasAnchor" number="1.12.4">
<h3><span class="header-section-number">1.12.4</span> Øvelse med CO2<a href="baser.html#%C3%B8velse-med-co2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>15)</strong> (<strong>t-test med CO2</strong>)</p>
<ul>
<li>Indlæs datasættet med kommandoen <code>data(CO2)</code>.</li>
<li>Opret en delmængde med kun observationer af “Quebec” (variablen <code>Type</code>).</li>
<li>Beregn den gennemsnitlige optagelse (variablen <code>uptake</code>) for hvert behandlingstype (variablen <code>Treatment</code>) i din delmængde ved hjælp af <code>tapply()</code>-funktionen.</li>
<li>Udfør en t-test ved hjælp af <code>t.test()</code>-funktionen for at sammenligne optagelsen mellem de to behandlinger i din delmængde.</li>
<li>Skriv en kort sætning med din konklusion.</li>
</ul>
</div>
<div id="ekstra-øvelser-med-andre-statistike-tests" class="section level3 hasAnchor" number="1.12.5">
<h3><span class="header-section-number">1.12.5</span> Ekstra øvelser med andre statistike tests<a href="baser.html#ekstra-%C3%B8velser-med-andre-statistike-tests" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>16)</strong> (<strong>Chi-squared</strong>)</p>
<p>Kør følgende kode til at få en tabel (selve koden er ikke vigtigt):</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="baser.html#cb128-1" tabindex="-1"></a>mytable <span class="ot">&lt;-</span> <span class="fu">structure</span>(</span>
<span id="cb128-2"><a href="baser.html#cb128-2" tabindex="-1"></a>    <span class="fu">c</span>(<span class="dv">80</span><span class="dt">L</span>, <span class="dv">97</span><span class="dt">L</span>, <span class="dv">372</span><span class="dt">L</span>, <span class="dv">136</span><span class="dt">L</span>, <span class="dv">87</span><span class="dt">L</span>, <span class="dv">119</span><span class="dt">L</span>),</span>
<span id="cb128-3"><a href="baser.html#cb128-3" tabindex="-1"></a>    <span class="at">.Dim =</span> <span class="dv">3</span><span class="sc">:</span><span class="dv">2</span>,</span>
<span id="cb128-4"><a href="baser.html#cb128-4" tabindex="-1"></a>    <span class="at">.Dimnames =</span> <span class="fu">structure</span>(</span>
<span id="cb128-5"><a href="baser.html#cb128-5" tabindex="-1"></a>      <span class="fu">list</span>(</span>
<span id="cb128-6"><a href="baser.html#cb128-6" tabindex="-1"></a>          <span class="fu">c</span>(<span class="st">&quot;First&quot;</span>, <span class="st">&quot;Second&quot;</span>, <span class="st">&quot;Third&quot;</span>),</span>
<span id="cb128-7"><a href="baser.html#cb128-7" tabindex="-1"></a>          <span class="fu">c</span>(<span class="st">&quot;Died&quot;</span>, <span class="st">&quot;Survived&quot;</span>)</span>
<span id="cb128-8"><a href="baser.html#cb128-8" tabindex="-1"></a>        ),</span>
<span id="cb128-9"><a href="baser.html#cb128-9" tabindex="-1"></a>      <span class="at">.Names =</span> <span class="fu">c</span>(<span class="st">&quot;Class&quot;</span>, <span class="st">&quot;Survival&quot;</span>)</span>
<span id="cb128-10"><a href="baser.html#cb128-10" tabindex="-1"></a>      ),</span>
<span id="cb128-11"><a href="baser.html#cb128-11" tabindex="-1"></a>    <span class="at">class =</span> <span class="st">&quot;table&quot;</span></span>
<span id="cb128-12"><a href="baser.html#cb128-12" tabindex="-1"></a>  )</span>
<span id="cb128-13"><a href="baser.html#cb128-13" tabindex="-1"></a></span>
<span id="cb128-14"><a href="baser.html#cb128-14" tabindex="-1"></a>mytable</span></code></pre></div>
<pre><code>##         Survival
## Class    Died Survived
##   First    80      136
##   Second   97       87
##   Third   372      119</code></pre>
<p>Tabellen beskriver antallet af passagerer ombord skibet ‘Titanic’, som sank den 15. april 1912 efter et sammenstød med et isbjerg 600 km sydøst for Halifax, Nova Scotia i Canada. Tabellen er opdelt i tre klasser (første-, anden-, tredjeklasse) og viser antallet af passagerer, som overlevede tragedien og antallet af passagerer, som desværre omkom.</p>
<ul>
<li><p>Benyt funktionen <code>chisq.test()</code> på tabellen.</p></li>
<li><p>Hvad er nulhypotesen til denne test?</p></li>
<li><p>Er testen signifikant?</p></li>
<li><p>Er passagerenes klasse og deres chance for at overleve uafhængige af hinanden?</p></li>
<li><p>Hvilken af de tre klasser havde den bedste chance for at overleve?</p></li>
</ul>
<p>Vi kommer til at arbejde meget mere med datasættet <code>Titanic</code> i emnet Tidyverse - dag 1!</p>
<p><strong>17)</strong> (<strong>Korrelationsanalyse</strong>)</p>
<p>Åbn datasættet <code>trees</code> og lav et spredningsplot / scatter plot med variablen <code>Girth</code> på x-aksen og variablen <code>Volume</code> på y-aksen.</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="baser.html#cb130-1" tabindex="-1"></a><span class="fu">data</span>(trees)</span>
<span id="cb130-2"><a href="baser.html#cb130-2" tabindex="-1"></a><span class="fu">summary</span>(trees)</span></code></pre></div>
<ul>
<li>Anvend funktionen <code>cor.test</code> for at teste, om der er en signifikant korrelation mellem de to variabler. Brug <code>method = "pearson"</code> (det er dog faktisk default).</li>
</ul>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="baser.html#cb131-1" tabindex="-1"></a><span class="fu">cor.test</span>(???, ???,<span class="at">method=</span><span class="st">&quot;pearson&quot;</span>)</span></code></pre></div>
<ul>
<li>Hvad er korrelationen mellem <code>Girth</code> og <code>Volume</code>? Anvend de log-transformerede værdier til variablen <code>Volume</code> inden du laver testen (dvs. brug <code>log()</code> funktionen).</li>
<li>Hvad er p-værdien? Er den signifikant?</li>
</ul>
<p><strong>18)</strong> (<strong>ANOVA</strong>)</p>
<p>OBS! Hvis du føler dig usikker med funktionen <code>lm()</code> - der kommer en video om det i morgen (i forbindelse med emnet R Markdown).</p>
<ul>
<li>Kør følgende kode til at lave variansanalysen, der tester nulhypotesen hvor den gennemsnitlige værdi af variablen <code>Sepal.Width</code> er ens for hver af de tre arter (variablen <code>Species</code>) fra datasættet <code>iris</code>:</li>
</ul>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="baser.html#cb132-1" tabindex="-1"></a><span class="fu">data</span>(iris)</span>
<span id="cb132-2"><a href="baser.html#cb132-2" tabindex="-1"></a></span>
<span id="cb132-3"><a href="baser.html#cb132-3" tabindex="-1"></a><span class="co">#model under H0: no difference according to group variable Species (1 just means &quot;fit overall mean&quot;)</span></span>
<span id="cb132-4"><a href="baser.html#cb132-4" tabindex="-1"></a>model_h0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sepal.Width <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> iris) </span>
<span id="cb132-5"><a href="baser.html#cb132-5" tabindex="-1"></a></span>
<span id="cb132-6"><a href="baser.html#cb132-6" tabindex="-1"></a><span class="co">#model under H1: each level of group variable Species has its own mean</span></span>
<span id="cb132-7"><a href="baser.html#cb132-7" tabindex="-1"></a>model_h1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sepal.Width <span class="sc">~</span> Species, <span class="at">data =</span> iris) </span>
<span id="cb132-8"><a href="baser.html#cb132-8" tabindex="-1"></a></span>
<span id="cb132-9"><a href="baser.html#cb132-9" tabindex="-1"></a><span class="co">#compare two models - significant p-value equates to choosing H1 model</span></span>
<span id="cb132-10"><a href="baser.html#cb132-10" tabindex="-1"></a><span class="fu">anova</span>(model_h0, model_h1)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: Sepal.Width ~ 1
## Model 2: Sepal.Width ~ Species
##   Res.Df    RSS Df Sum of Sq     F    Pr(&gt;F)    
## 1    149 28.307                                 
## 2    147 16.962  2    11.345 49.16 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="baser.html#cb134-1" tabindex="-1"></a><span class="co">#check assumptions for alternative model</span></span>
<span id="cb134-2"><a href="baser.html#cb134-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb134-3"><a href="baser.html#cb134-3" tabindex="-1"></a><span class="fu">plot</span>(model_h1, <span class="at">which =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-109-1.png" width="480" /></p>
<p>Kig på outputtet:</p>
<ul>
<li>Hvilken model reflekterer nulhypotesen?</li>
<li>Hvilken model reflekterer alternativhypotesen?</li>
<li>Hvor er p-værdien?</li>
<li>Er der en signifikant forskel i den gennemsnitlige <code>Sepal.Width</code> efter de forskellige <code>Species</code>?</li>
<li>Kan vi stole på testen (tjek forudsætninger til ANOVA).</li>
</ul>
<p><strong>19)</strong> (<strong>ANOVA</strong>)</p>
<p>Lav en lignende analyse på datasættet <code>chickwts</code> for at svare på spørgsmålet:</p>
<ul>
<li>Er der en forskel i den gennemsnitlige vægt (variablen <code>weight</code>) efter fodertypen (variablen <code>feed</code>)? Med andre ord, er vægt afhængig af fodertypen?</li>
</ul>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="baser.html#cb135-1" tabindex="-1"></a><span class="fu">data</span>(chickwts)</span></code></pre></div>
<p><strong>OBS! Hvis du er usikker med linær regression: se venligst videoerne til emnet R Markdown og kom tilbage til følgende spørgsmål</strong></p>
<p><strong>20)</strong> (<strong>Lineær regression</strong>)</p>
<ul>
<li>Brug <code>lm</code> til at lave en simpel lineær regression så at variablen <code>Volume</code> (response) er afhængig af variablen <code>Girth</code> (datasættet <code>trees</code>).</li>
</ul>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="baser.html#cb136-1" tabindex="-1"></a>mylm <span class="ot">&lt;-</span> <span class="fu">lm</span>(???, <span class="at">data =</span> trees)</span></code></pre></div>
<p>Brug <code>summary</code> på din model for at finde følgende værdier:</p>
<ul>
<li>Hvad er <code>r.squared</code>? (multiple)</li>
<li>Er variablen <code>Girth</code> signifikant?</li>
<li>Hvad er formlen på den bedste rette linje (husk formen y = ax + b)?</li>
</ul>
<p><strong>21)</strong> (<strong>Kort intro til multiple lineær regression</strong>)</p>
<p>Tag ovenstående model og tilføj variablen <code>Height</code> som en ekstra prædiktor (uafhængig) variabel i modellen med en “+” tegn:</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="baser.html#cb137-1" tabindex="-1"></a>mylm_height <span class="ot">&lt;-</span> <span class="fu">lm</span>(??? <span class="sc">~</span> ??? <span class="sc">+</span> ???, <span class="at">data =</span> rees) </span>
<span id="cb137-2"><a href="baser.html#cb137-2" tabindex="-1"></a><span class="fu">summary</span>(mylm_height)</span></code></pre></div>
<p><em>Bemærk at det ikke betyder, at de to variabler skal lægges sammen, men at vi vil have begge variabler i modellen som uafhængig variabler (med andre ord er <code>Volume</code> afhængig af både <code>Girth</code> og <code>Height</code>).</em></p>
<p>Benyt <code>summary</code> på modellen og prøv at finde følgende:</p>
<ul>
<li>Hvad er (multiple) r.squared værdien?</li>
<li>Hvor meget ændrer (multiple) r.squared værdien sig i forhold til modellen med kun variablen <code>Girth</code>?</li>
<li>Er <code>Volume</code> signifikant afhængig af <code>Height</code> (efter at man har taget højde for <code>Girth</code>)?</li>
</ul>
<p>Brug funktionen <code>anova</code> til at sammenligne modellen uden <code>Height</code> og modellen med <code>Height</code>.</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="baser.html#cb138-1" tabindex="-1"></a><span class="fu">anova</span>(<span class="co">#model without height,#model with height)</span></span></code></pre></div>
<p>Bemærk at i dette tilfælde er p-værdien fra ANOVA samme p-værdien fra <code>summary(mylm_height)</code>.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="rmarkdown.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
